<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit_advanced_ads_tracking
{
    public static $classMap = array (
        'AdvancedAds\\Tracking\\AMP' => __DIR__ . '/../..' . '/includes/class-amp.php',
        'AdvancedAds\\Tracking\\Ad_Limiter' => __DIR__ . '/../..' . '/includes/class-ad-limiter.php',
        'AdvancedAds\\Tracking\\Admin\\Ad_List_Table' => __DIR__ . '/../..' . '/includes/admin/class-ad-list-table.php',
        'AdvancedAds\\Tracking\\Admin\\Admin' => __DIR__ . '/../..' . '/includes/admin/class-admin.php',
        'AdvancedAds\\Tracking\\Admin\\Metaboxes' => __DIR__ . '/../..' . '/includes/admin/class-metaboxes.php',
        'AdvancedAds\\Tracking\\Admin\\Page_Database' => __DIR__ . '/../..' . '/includes/admin/class-page-database.php',
        'AdvancedAds\\Tracking\\Admin\\Page_Stats' => __DIR__ . '/../..' . '/includes/admin/class-page-stats.php',
        'AdvancedAds\\Tracking\\Admin\\Quick_Bulk_Edit' => __DIR__ . '/../..' . '/includes/admin/class-quick-bulk-edit.php',
        'AdvancedAds\\Tracking\\Admin\\Quick_Edit' => __DIR__ . '/../..' . '/includes/admin/class-quick-edit.php',
        'AdvancedAds\\Tracking\\Admin\\Settings' => __DIR__ . '/../..' . '/includes/admin/class-settings.php',
        'AdvancedAds\\Tracking\\Admin\\WordPress_Dashboard' => __DIR__ . '/../..' . '/includes/admin/class-wordpress-dashboard.php',
        'AdvancedAds\\Tracking\\Ajax' => __DIR__ . '/../..' . '/includes/class-ajax.php',
        'AdvancedAds\\Tracking\\Assets_Registry' => __DIR__ . '/../..' . '/includes/class-assets-registry.php',
        'AdvancedAds\\Tracking\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\Tracking\\Bootstrap' => __DIR__ . '/../..' . '/includes/class-bootstrap.php',
        'AdvancedAds\\Tracking\\Compatibility' => __DIR__ . '/../..' . '/includes/class-compatibility.php',
        'AdvancedAds\\Tracking\\Constants' => __DIR__ . '/../..' . '/includes/class-constants.php',
        'AdvancedAds\\Tracking\\Crons\\Jobs' => __DIR__ . '/../..' . '/includes/crons/class-jobs.php',
        'AdvancedAds\\Tracking\\Crons\\Reporting_Emails' => __DIR__ . '/../..' . '/includes/crons/class-reporting-emails.php',
        'AdvancedAds\\Tracking\\Database' => __DIR__ . '/../..' . '/includes/class-database.php',
        'AdvancedAds\\Tracking\\Db_Operations' => __DIR__ . '/../..' . '/includes/class-db-operations.php',
        'AdvancedAds\\Tracking\\Debugger' => __DIR__ . '/../..' . '/includes/class-debugger.php',
        'AdvancedAds\\Tracking\\Frontend\\Ajax_Tracking' => __DIR__ . '/../..' . '/includes/frontend/class-ajax-tracking.php',
        'AdvancedAds\\Tracking\\Frontend\\Analytics_Tracking' => __DIR__ . '/../..' . '/includes/frontend/class-analytics-tracking.php',
        'AdvancedAds\\Tracking\\Frontend\\Database_Tracking' => __DIR__ . '/../..' . '/includes/frontend/class-database-tracking.php',
        'AdvancedAds\\Tracking\\Frontend\\Frontend_Tracking' => __DIR__ . '/../..' . '/includes/frontend/class-frontend-tracking.php',
        'AdvancedAds\\Tracking\\Frontend\\Public_Stats' => __DIR__ . '/../..' . '/includes/frontend/class-public-stats.php',
        'AdvancedAds\\Tracking\\Frontend\\Tracking' => __DIR__ . '/../..' . '/includes/frontend/class-tracking.php',
        'AdvancedAds\\Tracking\\Frontend\\Tracking_Link' => __DIR__ . '/../..' . '/includes/frontend/class-tracking-link.php',
        'AdvancedAds\\Tracking\\Frontend\\Tracking_Scripts' => __DIR__ . '/../..' . '/includes/frontend/class-tracking-scripts.php',
        'AdvancedAds\\Tracking\\Helpers' => __DIR__ . '/../..' . '/includes/class-helpers.php',
        'AdvancedAds\\Tracking\\Installation\\Install' => __DIR__ . '/../..' . '/includes/installation/class-install.php',
        'AdvancedAds\\Tracking\\Installation\\Tracking_Installer' => __DIR__ . '/../..' . '/includes/installation/class-tracking-installer.php',
        'AdvancedAds\\Tracking\\Installation\\Uninstall' => __DIR__ . '/../..' . '/includes/installation/class-uninstall.php',
        'AdvancedAds\\Tracking\\Options' => __DIR__ . '/../..' . '/includes/class-options.php',
        'AdvancedAds\\Tracking\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'AdvancedAds\\Tracking\\Public_Ad' => __DIR__ . '/../..' . '/includes/class-public-ad.php',
        'AdvancedAds\\Tracking\\Shortcodes' => __DIR__ . '/../..' . '/includes/class-shortcodes.php',
        'AdvancedAds\\Tracking\\Upgrades' => __DIR__ . '/../..' . '/includes/class-upgrades.php',
        'AdvancedAds\\Tracking\\Utilities\\Data' => __DIR__ . '/../..' . '/includes/utilities/class-data.php',
        'AdvancedAds\\Tracking\\Utilities\\Email' => __DIR__ . '/../..' . '/includes/utilities/class-email.php',
        'AdvancedAds\\Tracking\\Utilities\\Tracking' => __DIR__ . '/../..' . '/includes/utilities/class-tracking.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit_advanced_ads_tracking::$classMap;

        }, null, ClassLoader::class);
    }
}
