<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit_advanced_ads_gam
{
    public static $classMap = array (
        'AdvancedAds\\GAM\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\GAM\\Bootstrap' => __DIR__ . '/../..' . '/includes/class-bootstrap.php',
        'AdvancedAds\\GAM\\Frontend' => __DIR__ . '/../..' . '/includes/class-frontend.php',
        'AdvancedAds\\GAM\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'AdvancedAds\\GAM\\Plugin_Types' => __DIR__ . '/../..' . '/includes/class-plugin-types.php',
        'AdvancedAds\\GAM\\Types\\GAM' => __DIR__ . '/../..' . '/includes/types/type-gam.php',
        'Advanced_Ads_Gam_Ad' => __DIR__ . '/../..' . '/includes/class-advanced-ads-gam-ad.php',
        'Advanced_Ads_Gam_Admin' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-admin.php',
        'Advanced_Ads_Gam_Ajax' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-ajax.php',
        'Advanced_Ads_Gam_Api' => __DIR__ . '/../..' . '/admin/interface-advanced-ads-gam-api.php',
        'Advanced_Ads_Gam_Api_Rest' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-api-rest.php',
        'Advanced_Ads_Gam_Api_Soap' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-api-soap.php',
        'Advanced_Ads_Gam_Importer' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-importer.php',
        'Advanced_Ads_Gam_Oauth2' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-oauth2.php',
        'Advanced_Ads_Network_Gam' => __DIR__ . '/../..' . '/includes/class-advanced-ads-network-gam.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit_advanced_ads_gam::$classMap;

        }, null, ClassLoader::class);
    }
}
