<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\GAM\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'AdvancedAds\\GAM\\Bootstrap' => $baseDir . '/includes/class-bootstrap.php',
    'AdvancedAds\\GAM\\Frontend' => $baseDir . '/includes/class-frontend.php',
    'AdvancedAds\\GAM\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'AdvancedAds\\GAM\\Plugin_Types' => $baseDir . '/includes/class-plugin-types.php',
    'AdvancedAds\\GAM\\Types\\GAM' => $baseDir . '/includes/types/type-gam.php',
    'Advanced_Ads_Gam_Ad' => $baseDir . '/includes/class-advanced-ads-gam-ad.php',
    'Advanced_Ads_Gam_Admin' => $baseDir . '/admin/class-advanced-ads-gam-admin.php',
    'Advanced_Ads_Gam_Ajax' => $baseDir . '/admin/class-advanced-ads-gam-ajax.php',
    'Advanced_Ads_Gam_Api' => $baseDir . '/admin/interface-advanced-ads-gam-api.php',
    'Advanced_Ads_Gam_Api_Rest' => $baseDir . '/admin/class-advanced-ads-gam-api-rest.php',
    'Advanced_Ads_Gam_Api_Soap' => $baseDir . '/admin/class-advanced-ads-gam-api-soap.php',
    'Advanced_Ads_Gam_Importer' => $baseDir . '/admin/class-advanced-ads-gam-importer.php',
    'Advanced_Ads_Gam_Oauth2' => $baseDir . '/admin/class-advanced-ads-gam-oauth2.php',
    'Advanced_Ads_Network_Gam' => $baseDir . '/includes/class-advanced-ads-network-gam.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
