<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit19cc5bc20e82ac4c32a7cc72b990c6b3
{
    public static $classMap = array (
        'AdvancedAds\\SellingAds\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\SellingAds\\Bootstrap' => __DIR__ . '/../..' . '/includes/class-bootstrap.php',
        'AdvancedAds\\SellingAds\\Installation\\Install' => __DIR__ . '/../..' . '/includes/installation/class-install.php',
        'AdvancedAds\\SellingAds\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'Advanced_Ads_Selling' => __DIR__ . '/../..' . '/public/public.php',
        'Advanced_Ads_Selling_Admin' => __DIR__ . '/../..' . '/admin/admin.php',
        'Advanced_Ads_Selling_Admin_Ad_Order_Meta_Box' => __DIR__ . '/../..' . '/admin/includes/ad-order-meta-box.php',
        'Advanced_Ads_Selling_Admin_Ad_Product' => __DIR__ . '/../..' . '/admin/includes/ad-product.php',
        'Advanced_Ads_Selling_Admin_Order_Page' => __DIR__ . '/../..' . '/admin/includes/order-page.php',
        'Advanced_Ads_Selling_Admin_Placements' => __DIR__ . '/../..' . '/admin/includes/placements.php',
        'Advanced_Ads_Selling_Ads_Page_Endpoint' => __DIR__ . '/../..' . '/classes/public-ads-page-endpoint.php',
        'Advanced_Ads_Selling_Ajax' => __DIR__ . '/../..' . '/public/includes/ajax.php',
        'Advanced_Ads_Selling_Notifications' => __DIR__ . '/../..' . '/classes/notifications.php',
        'Advanced_Ads_Selling_Order' => __DIR__ . '/../..' . '/classes/order.php',
        'Advanced_Ads_Selling_Plugin' => __DIR__ . '/../..' . '/classes/plugin.php',
        'Advanced_Ads_Selling_Public_Order' => __DIR__ . '/../..' . '/public/includes/order.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WC_Product_Advanced_Ad' => __DIR__ . '/../..' . '/classes/WooCommerce-product.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit19cc5bc20e82ac4c32a7cc72b990c6b3::$classMap;

        }, null, ClassLoader::class);
    }
}
