<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\SellingAds\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'AdvancedAds\\SellingAds\\Bootstrap' => $baseDir . '/includes/class-bootstrap.php',
    'AdvancedAds\\SellingAds\\Installation\\Install' => $baseDir . '/includes/installation/class-install.php',
    'AdvancedAds\\SellingAds\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'Advanced_Ads_Selling' => $baseDir . '/public/public.php',
    'Advanced_Ads_Selling_Admin' => $baseDir . '/admin/admin.php',
    'Advanced_Ads_Selling_Admin_Ad_Order_Meta_Box' => $baseDir . '/admin/includes/ad-order-meta-box.php',
    'Advanced_Ads_Selling_Admin_Ad_Product' => $baseDir . '/admin/includes/ad-product.php',
    'Advanced_Ads_Selling_Admin_Order_Page' => $baseDir . '/admin/includes/order-page.php',
    'Advanced_Ads_Selling_Admin_Placements' => $baseDir . '/admin/includes/placements.php',
    'Advanced_Ads_Selling_Ads_Page_Endpoint' => $baseDir . '/classes/public-ads-page-endpoint.php',
    'Advanced_Ads_Selling_Ajax' => $baseDir . '/public/includes/ajax.php',
    'Advanced_Ads_Selling_Notifications' => $baseDir . '/classes/notifications.php',
    'Advanced_Ads_Selling_Order' => $baseDir . '/classes/order.php',
    'Advanced_Ads_Selling_Plugin' => $baseDir . '/classes/plugin.php',
    'Advanced_Ads_Selling_Public_Order' => $baseDir . '/public/includes/order.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WC_Product_Advanced_Ad' => $baseDir . '/classes/WooCommerce-product.php',
);
