<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit_advanced_ads_responsive
{
    public static $classMap = array (
        'AdvancedAds\\AMP\\AdSense' => __DIR__ . '/../..' . '/includes/class-adsense.php',
        'AdvancedAds\\AMP\\Amp' => __DIR__ . '/../..' . '/includes/class-amp.php',
        'AdvancedAds\\AMP\\Amp_Ad' => __DIR__ . '/../..' . '/includes/class-amp-ad.php',
        'AdvancedAds\\AMP\\Amp_Type' => __DIR__ . '/../..' . '/includes/class-amp-type.php',
        'AdvancedAds\\AMP\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\AMP\\Bootstrap' => __DIR__ . '/../..' . '/includes/class-bootstrap.php',
        'AdvancedAds\\AMP\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'AdvancedAds\\AMP\\Tablet' => __DIR__ . '/../..' . '/includes/class-tablet.php',
        'AdvancedAds\\AMP\\admin\\AdSense' => __DIR__ . '/../..' . '/includes/admin/class-adsense.php',
        'AdvancedAds\\AMP\\admin\\Amp' => __DIR__ . '/../..' . '/includes/admin/class-amp.php',
        'AdvancedAds\\AMP\\admin\\Backend' => __DIR__ . '/../..' . '/includes/admin/class-backend.php',
        'AdvancedAds\\AMP\\frontend\\Amp' => __DIR__ . '/../..' . '/includes/frontend/class-amp.php',
        'AdvancedAds\\AMP\\frontend\\Amp_Compat' => __DIR__ . '/../..' . '/includes/frontend/class-amp-compat.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit_advanced_ads_responsive::$classMap;

        }, null, ClassLoader::class);
    }
}
