<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\AMP\\AdSense' => $baseDir . '/includes/class-adsense.php',
    'AdvancedAds\\AMP\\Amp' => $baseDir . '/includes/class-amp.php',
    'AdvancedAds\\AMP\\Amp_Ad' => $baseDir . '/includes/class-amp-ad.php',
    'AdvancedAds\\AMP\\Amp_Type' => $baseDir . '/includes/class-amp-type.php',
    'AdvancedAds\\AMP\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'AdvancedAds\\AMP\\Bootstrap' => $baseDir . '/includes/class-bootstrap.php',
    'AdvancedAds\\AMP\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'AdvancedAds\\AMP\\Tablet' => $baseDir . '/includes/class-tablet.php',
    'AdvancedAds\\AMP\\admin\\AdSense' => $baseDir . '/includes/admin/class-adsense.php',
    'AdvancedAds\\AMP\\admin\\Amp' => $baseDir . '/includes/admin/class-amp.php',
    'AdvancedAds\\AMP\\admin\\Backend' => $baseDir . '/includes/admin/class-backend.php',
    'AdvancedAds\\AMP\\frontend\\Amp' => $baseDir . '/includes/frontend/class-amp.php',
    'AdvancedAds\\AMP\\frontend\\Amp_Compat' => $baseDir . '/includes/frontend/class-amp-compat.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
