<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\Layer\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'AdvancedAds\\Layer\\Bootstrap' => $baseDir . '/includes/class-bootstrap.php',
    'AdvancedAds\\Layer\\Placements\\Placement_Layer' => $baseDir . '/includes/placements/class-placement-layer.php',
    'AdvancedAds\\Layer\\Placements\\Placement_Types' => $baseDir . '/includes/placements/class-placement-types.php',
    'AdvancedAds\\Layer\\Placements\\Types\\Layer' => $baseDir . '/includes/placements/types/class-layer.php',
    'AdvancedAds\\Layer\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
