<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2e93b5002ab640c1cc04f87ee5a45aed
{
    public static $classMap = array (
        'AdvancedAds\\Layer\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\Layer\\Bootstrap' => __DIR__ . '/../..' . '/includes/class-bootstrap.php',
        'AdvancedAds\\Layer\\Placements\\Placement_Layer' => __DIR__ . '/../..' . '/includes/placements/class-placement-layer.php',
        'AdvancedAds\\Layer\\Placements\\Placement_Types' => __DIR__ . '/../..' . '/includes/placements/class-placement-types.php',
        'AdvancedAds\\Layer\\Placements\\Types\\Layer' => __DIR__ . '/../..' . '/includes/placements/types/class-layer.php',
        'AdvancedAds\\Layer\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit2e93b5002ab640c1cc04f87ee5a45aed::$classMap;

        }, null, ClassLoader::class);
    }
}
