/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_comments` (
  `comment_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT 0,
  `comment_author` tinytext NOT NULL,
  `comment_author_email` varchar(100) NOT NULL DEFAULT '',
  `comment_author_url` varchar(200) NOT NULL DEFAULT '',
  `comment_author_IP` varchar(100) NOT NULL DEFAULT '',
  `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content` text NOT NULL,
  `comment_karma` int(11) NOT NULL DEFAULT 0,
  `comment_approved` varchar(20) NOT NULL DEFAULT '1',
  `comment_agent` varchar(255) NOT NULL DEFAULT '',
  `comment_type` varchar(20) NOT NULL DEFAULT 'comment',
  `comment_parent` bigint(20) unsigned NOT NULL DEFAULT 0,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`comment_ID`),
  KEY `comment_post_ID` (`comment_post_ID`),
  KEY `comment_approved_date_gmt` (`comment_approved`,`comment_date_gmt`),
  KEY `comment_date_gmt` (`comment_date_gmt`),
  KEY `comment_parent` (`comment_parent`),
  KEY `comment_author_email` (`comment_author_email`(10)),
  KEY `woo_idx_comment_type` (`comment_type`),
  KEY `woo_idx_comment_date_type` (`comment_date_gmt`,`comment_type`,`comment_approved`,`comment_post_ID`),
  KEY `woo_idx_comment_approved_type` (`comment_approved`,`comment_type`,`comment_post_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=137 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (2,228,'Reza','rehe1373@ymail.com','http://rezadeveloper.com/newstopia/','2.184.99.149','2016-12-22 21:25:04','2016-12-22 21:25:04','sed lacus condimentum malesuada. In hac habitasse platea dictumst. Integer felis ipsum, laoreet in gravida in,',0,'post-trashed','','comment',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (10,90007023,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-16 15:37:10','2025-01-16 15:37:10','Stock hold of 60 minutes applied to: <br>- Norton 360 Standard - 1-Year / 1-Device - USA/Canada (#90006987) &times; 1<br>- McAfee Total Protection - 1-Year / 3-Devices - USA/Canada (#90006997) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (11,90007023,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-16 15:37:10','2025-01-16 15:37:10','Stock levels reduced: Norton 360 Standard - 1-Year / 1-Device - USA/Canada (#90006987) 12&rarr;11, McAfee Total Protection - 1-Year / 3-Devices - USA/Canada (#90006997) 6&rarr;5',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (12,90007023,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-16 15:37:10','2025-01-16 15:37:10','Awaiting BACS payment Order status changed from Pending payment to On hold.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (13,90007025,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-17 05:44:14','2025-01-17 05:44:14','Stock hold of 60 minutes applied to: <br>- McAfee Total Protection - 1-Year / 5-Devices - USA/Canada (#90006998) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (14,90007025,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-17 05:44:14','2025-01-17 05:44:14','Stock levels reduced: McAfee Total Protection - 1-Year / 5-Devices - USA/Canada (#90006998) 9&rarr;8',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (15,90007025,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-17 05:44:14','2025-01-17 05:44:14','Awaiting BACS payment Order status changed from Pending payment to On hold.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (16,90007086,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-17 07:44:24','2025-01-17 07:44:24','Awaiting BACS payment Order status changed from Pending payment to On hold.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (17,90007086,'Divyanshu Tiwari','divyanshu.tiwari@thecodeyogi.com','','','2025-01-17 07:45:21','2025-01-17 07:45:21','Order status changed by bulk edit. Order status changed from On hold to Completed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (18,90007181,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-17 12:05:50','2025-01-17 12:05:50','Stock hold of 60 minutes applied to: <br>- Norton 360 Standard - 1-Year / 1-Device - USA/Canada (#90006987) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (19,90007181,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-17 12:05:51','2025-01-17 12:05:51','Stock levels reduced: Norton 360 Standard - 1-Year / 1-Device - USA/Canada (#90006987) 11&rarr;10',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (20,90007181,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-17 12:05:51','2025-01-17 12:05:51','Awaiting BACS payment Order status changed from Pending payment to On hold.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (21,90007181,'Divyanshu Tiwari','divyanshu.tiwari@thecodeyogi.com','','','2025-01-17 12:06:23','2025-01-17 12:06:23','Order status changed by bulk edit. Order status changed from On hold to Completed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (22,90007265,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-20 09:35:23','2025-01-20 09:35:23','Stock hold of 60 minutes applied to: <br>- Watchdog Anti-Virus - 1-Year / 3-PC (#90007092) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (23,90007265,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-20 09:35:23','2025-01-20 09:35:23','Stock levels reduced: Watchdog Anti-Virus - 1-Year / 3-PC (#90007092) 20&rarr;19',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (24,90007265,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-20 09:35:23','2025-01-20 09:35:23','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (25,90007439,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-21 15:23:28','2025-01-21 15:23:28','Stock hold of 60 minutes applied to: <br>- Malwarebytes Premium - 1-Year / 10-Device (#90007185) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (26,90007439,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-21 15:23:28','2025-01-21 15:23:28','Stock levels reduced: Malwarebytes Premium - 1-Year / 10-Device (#90007185) 54&rarr;53',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (27,90007439,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-21 15:23:28','2025-01-21 15:23:28','Awaiting BACS payment Order status changed from Pending payment to On hold.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (28,90007168,'???? Notification- SENDING 0,75432988 bitcoin. Continue =&gt;&gt; https://telegra.ph/Get-BTC-right-now-01-22?hs=6d60c4b30f29c4e91491cd96735d99d6&amp; ????','aurorabnkwy@gmailbrt.com','','5.255.121.11','2025-01-25 16:22:09','2025-01-25 16:22:09','s1c6sj',0,'1','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (29,90007189,'???? You have received 1 email ? 285411. Open &gt;&gt;&gt; https://telegra.ph/Get-BTC-right-now-01-22?hs=d48fe16168f27a4f6dc634f7c5c69c5c&amp; ????','aurorabnkwy@gmailbrt.com','','192.42.116.178','2025-01-25 16:22:28','2025-01-25 16:22:28','wgqa4i',0,'1','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (31,90007264,'???? You have received a message(-s) # 13659. Open &gt;&gt;&gt; https://telegra.ph/Get-BTC-right-now-01-22?hs=3ed5f33429ebc54c5f671419267f1600&amp; ????','aurorabnkwy@gmailbrt.com','','185.220.100.254','2025-01-25 16:23:29','2025-01-25 16:23:29','4k4h8x',0,'1','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (32,90007266,'???? You have a email ? 148482. Open - https://telegra.ph/Get-BTC-right-now-01-22?hs=1d529e5cc1ec8d8f16d2d666020613ca&amp; ????','aurorabnkwy@gmailbrt.com','','185.220.101.60','2025-01-25 16:23:46','2025-01-25 16:23:46','tvxxyn',0,'1','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (33,90007364,'???? You have a transfer from us. Confirm =&gt; https://telegra.ph/Get-BTC-right-now-01-22?hs=5a9cd1edef67b7d6ea920023655ebca9&amp; ????','aurorabnkwy@gmailbrt.com','','192.42.116.178','2025-01-25 16:24:04','2025-01-25 16:24:04','ztym9v',0,'1','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (35,90006988,'???? You have received a message ? 887305. Go - https://telegra.ph/Get-BTC-right-now-01-22?hs=911ef51f0e9c7f43b09228efa8dc51bb&amp; ????','aurorabnkwy@gmailbrt.com','','45.84.107.198','2025-01-25 16:24:37','2025-01-25 16:24:37','4ihkgc',0,'post-trashed','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (36,90006991,'???? Ticket; Operation ?HX99. NEXT &gt;&gt; https://telegra.ph/Get-BTC-right-now-01-22?hs=acb8ca804985a13e58b98e49be6fc22c&amp; ????','aurorabnkwy@gmailbrt.com','','192.42.116.187','2025-01-25 16:24:56','2025-01-25 16:24:56','qc1j8x',0,'post-trashed','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (38,90006992,'???? We send a transaction from user. GET =&gt;&gt; https://telegra.ph/Get-BTC-right-now-01-22?hs=5399867fc8f9753c0cf7acaf0b3fd79c&amp; ????','aurorabnkwy@gmailbrt.com','','192.42.116.210','2025-01-25 16:25:43','2025-01-25 16:25:43','5crpmw',0,'1','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (40,90007090,'???? Sending a gift from unknown user. Next =&gt; https://telegra.ph/Get-BTC-right-now-01-22?hs=a187886756ac797aeb5d9ed1633ce65c&amp; ????','aurorabnkwy@gmailbrt.com','','192.42.116.210','2025-01-25 16:26:17','2025-01-25 16:26:17','8rbbqo',0,'1','Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 YaBrowser/15.12.1.6476 Yowser/2.5 Safari/537.36','review',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (42,90007458,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-28 17:01:07','2025-01-28 17:01:07','Stock hold of 60 minutes applied to: <br>- McAfee Internet Security - 1-Year / 3-Device (#90007229) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (43,90007458,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-28 17:01:07','2025-01-28 17:01:07','Stock levels reduced: McAfee Internet Security - 1-Year / 3-Device (#90007229) 35&rarr;34',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (44,90007458,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-01-28 17:01:07','2025-01-28 17:01:07','Awaiting BACS payment Order status changed from Pending payment to On hold.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (45,90007469,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:10:29','2025-02-12 14:10:29','Stock hold of 60 minutes applied to: <br>- Watchdog Anti-Malware - 3-Year / 1-PC (#90007143) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (46,90007469,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:10:34','2025-02-12 14:10:34','Stock levels reduced: Watchdog Anti-Malware - 3-Year / 1-PC (#90007143) 45&rarr;44',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (47,90007469,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:10:36','2025-02-12 14:10:36','Order status changed from Pending payment to Completed.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (48,90007469,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:10:36','2025-02-12 14:10:36','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$1.46</p>\n<p>Net payout: $38.53 USD</p>\n</div>',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (49,90007469,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:10:37','2025-02-12 14:10:37','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>39.99</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3Qrge42HeNMDbl9A1sc5Wky4\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3Qrge42HeNMDbl9A1sc5Wky4</a>).',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (50,90007470,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:36:14','2025-02-12 14:36:14','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (51,90007470,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:36:19','2025-02-12 14:36:19','Stock levels reduced: Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) 50&rarr;49',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (52,90007470,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:36:29','2025-02-12 14:36:29','Order status changed from Pending payment to Completed.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (53,90007470,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:36:30','2025-02-12 14:36:30','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>24.95</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3Qrh302HeNMDbl9A19xCo7Hp\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3Qrh302HeNMDbl9A19xCo7Hp</a>).',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (54,90007470,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-12 14:36:34','2025-02-12 14:36:34','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$1.02</p>\n<p>Net payout: $23.93 USD</p>\n</div>',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (55,90007474,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:12:29','2025-02-13 10:12:29','Stock hold of 60 minutes applied to: <br>- McAfee Internet Security - 1-Year / 3-Device (#90006994) &times; 1<br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (56,90007474,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:12:37','2025-02-13 10:12:37','Stock levels reduced: McAfee Internet Security - 1-Year / 3-Device (#90006994) 50&rarr;49, Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) 49&rarr;48',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (57,90007474,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:12:38','2025-02-13 10:12:38','Error during status transition. License Keys are invalid.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (58,90007474,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:12:38','2025-02-13 10:12:38','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>74.94</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3QrzPJ2HeNMDbl9A0bejRXh2\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3QrzPJ2HeNMDbl9A0bejRXh2</a>).',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (59,90007474,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:12:40','2025-02-13 10:12:40','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$2.47</p>\n<p>Net payout: $72.47 USD</p>\n</div>',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (60,90007476,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:20:57','2025-02-13 10:20:57','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (61,90007476,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:21:01','2025-02-13 10:21:01','Stock levels reduced: Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) 48&rarr;47',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (62,90007476,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:21:22','2025-02-13 10:21:22','Order status changed from Pending payment to Completed.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (63,90007476,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:21:23','2025-02-13 10:21:23','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>1.95</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3QrzXT2HeNMDbl9A1MVaGEA0\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3QrzXT2HeNMDbl9A1MVaGEA0</a>).',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (64,90007476,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:21:29','2025-02-13 10:21:29','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$0.36</p>\n<p>Net payout: $1.59 USD</p>\n</div>',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (65,90007477,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:25:48','2025-02-13 10:25:48','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (66,90007477,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:25:52','2025-02-13 10:25:52','Stock levels reduced: Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) 47&rarr;46',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (67,90007477,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:26:10','2025-02-13 10:26:10','Order status changed from Pending payment to Completed.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (68,90007477,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:26:11','2025-02-13 10:26:11','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>1.95</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3QrzcA2HeNMDbl9A0FhK0FfV\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3QrzcA2HeNMDbl9A0FhK0FfV</a>).',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (69,90007477,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:27:38','2025-02-13 10:27:38','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$0.36</p>\n<p>Net payout: $1.59 USD</p>\n</div>',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (70,90007478,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:41:47','2025-02-13 10:41:47','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (71,90007478,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:41:51','2025-02-13 10:41:51','Stock levels reduced: Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) 46&rarr;45',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (72,90007478,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:42:01','2025-02-13 10:42:01','Order status changed from Pending payment to Completed.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (73,90007478,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:42:02','2025-02-13 10:42:02','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>1.95</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3Qrzrd2HeNMDbl9A0T50L950\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3Qrzrd2HeNMDbl9A0T50L950</a>).',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (74,90007478,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-13 10:42:29','2025-02-13 10:42:29','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$0.36</p>\n<p>Net payout: $1.59 USD</p>\n</div>',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (75,90007481,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 11:03:46','2025-02-14 11:03:46','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) &times; 1',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (76,90007481,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 11:03:51','2025-02-14 11:03:51','Stock levels reduced: Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) 45&rarr;44',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (77,90007481,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 11:03:53','2025-02-14 11:03:53','Order status changed from Pending payment to Completed.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (78,90007481,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 11:03:54','2025-02-14 11:03:54','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>1.95</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3QsMgU2HeNMDbl9A0y3LbJ5u\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3QsMgU2HeNMDbl9A0y3LbJ5u</a>).',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (79,90007481,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 11:04:01','2025-02-14 11:04:01','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$0.36</p>\n<p>Net payout: $1.59 USD</p>\n</div>',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (80,90007487,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 12:00:19','2025-02-14 12:00:19','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) &times; 3',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (81,90007487,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 12:00:24','2025-02-14 12:00:24','Stock levels reduced: Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (#90007366) 44&rarr;41',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (82,90007487,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 12:00:26','2025-02-14 12:00:26','Order status changed from Pending payment to Completed.',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (83,90007487,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 12:00:27','2025-02-14 12:00:27','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>5.85</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3QsNZC2HeNMDbl9A0pYQ4FUm\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3QsNZC2HeNMDbl9A0pYQ4FUm</a>).',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (84,90007487,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-02-14 12:00:29','2025-02-14 12:00:29','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$0.47</p>\n<p>Net payout: $5.38 USD</p>\n</div>',0,'','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (85,90007366,'Anurag Handique','dikshit@thecodeyogi.com','https://antiviruspointorgdomainonly.wpcomstaging.com','223.233.64.37','2025-02-14 12:09:22','2025-02-14 12:09:22','\"Been using this antivirus for months, and it works great! My system runs smoothly, and I feel secure knowing it\'s protecting me from threats. Totally worth it!\"',0,'post-trashed','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36','comment',0,1);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (86,90007491,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-06-18 07:11:01','2025-06-18 07:11:01','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (AVP-7X3G9L5T) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (87,90007491,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-06-18 07:11:05','2025-06-18 07:11:05','Stock levels reduced: Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (AVP-7X3G9L5T) 41&rarr;40',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (88,90007491,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-06-18 07:11:13','2025-06-18 07:11:13','Order status changed from Pending payment to Completed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (89,90007491,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-06-18 07:11:16','2025-06-18 07:11:16','<strong>Fee details:</strong><div class=\"captured-event-details\">\n<p>Base fee (2.9% + $0.30): -$0.36</p>\n<p>Net payout: $1.59 USD</p>\n</div>',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (90,90007491,'WooCommerce','woocommerce@antiviruspoint.com','','','2025-06-18 07:11:22','2025-06-18 07:11:22','A payment of <span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>1.95</bdi></span> was <strong>successfully charged</strong> using WooPayments (<a href=\"https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/transactions/details&id=pi_3RbG9D2HeNMDbl9A1y3bstTG\" target=\"_blank\" rel=\"noopener noreferrer\">pi_3RbG9D2HeNMDbl9A1y3bstTG</a>).',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (92,90007660,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-23 17:34:09','2025-06-23 17:34:09','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (#90007364) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (93,90007660,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-23 19:10:55','2025-06-23 19:10:55','Unpaid order cancelled - time limit reached. Order status changed from Pending payment to Cancelled.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (94,90007660,'madav6310','madav6310@gmail.com','','','2025-06-23 20:35:21','2025-06-23 20:35:21','Order details manually sent to customer.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (95,90007660,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-23 20:38:45','2025-06-23 20:38:45','Stock levels reduced: Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (#90007364) 50&rarr;49',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (96,90007660,'madav6310','madav6310@gmail.com','','','2025-06-23 20:38:45','2025-06-23 20:38:45','Order status changed from Cancelled to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (97,90007660,'madav6310','madav6310@gmail.com','','','2025-06-23 20:38:48','2025-06-23 20:38:48','Order details manually sent to customer.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (98,90007023,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-23 20:52:21','2025-06-23 20:52:21','Error during status transition. License Keys are invalid.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (99,90007025,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-23 20:52:21','2025-06-23 20:52:21','Error during status transition. License Keys are invalid.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (100,90007439,'madav6310','madav6310@gmail.com','','','2025-06-23 20:52:23','2025-06-23 20:52:23','Order status changed by bulk edit. Order status changed from On hold to Completed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (101,90007458,'madav6310','madav6310@gmail.com','','','2025-06-23 20:52:24','2025-06-23 20:52:24','Order status changed by bulk edit. Order status changed from On hold to Completed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (102,90007660,'madav6310','madav6310@gmail.com','','','2025-06-23 20:52:52','2025-06-23 20:52:52','Order status changed by bulk edit. Order status changed from Processing to Completed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (103,90007732,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-25 13:18:03','2025-06-25 13:18:03','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (#90007364) &times; 1<br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (AVP-7X3G9L5T) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (104,90007732,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-25 13:19:00','2025-06-25 13:19:00','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (#90007364) &times; 1<br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (AVP-7X3G9L5T) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (105,90007732,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-25 14:36:11','2025-06-25 14:36:11','Unpaid order cancelled - time limit reached. Order status changed from Pending payment to Cancelled.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (106,90007744,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-27 19:05:05','2025-06-27 19:05:05','Stock hold of 60 minutes applied to: <br>- Norton 360 Standard - 1-Year / 1-Device - USA/Canada (#90006987) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (107,90007744,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-27 19:06:09','2025-06-27 19:06:09','Stock hold of 60 minutes applied to: <br>- Norton 360 Standard - 1-Year / 1-Device - USA/Canada (#90006987) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (108,90007744,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-27 19:06:09','2025-06-27 19:06:09','Stock levels reduced: Norton 360 Standard - 1-Year / 1-Device - USA/Canada (#90006987) 10&rarr;9',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (109,90007744,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-27 19:06:09','2025-06-27 19:06:09','Awaiting check payment Order status changed from Pending payment to On hold.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (110,90007745,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-27 19:18:04','2025-06-27 19:18:04','Stock hold of 60 minutes applied to: <br>- McAfee Total Protection - 1-Year / 10-Devices - Europe/UK (#90007267) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (111,90007745,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-27 21:08:38','2025-06-27 21:08:38','Unpaid order cancelled - time limit reached. Order status changed from Pending payment to Cancelled.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (112,90007801,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-28 16:51:59','2025-06-28 16:51:59','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (AVP-7X3G9L5T) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (113,90007801,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-28 16:54:26','2025-06-28 16:54:26','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe (AVP-7X3G9L5T) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (114,90007801,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-28 18:39:34','2025-06-28 18:39:34','Unpaid order cancelled - time limit reached. Order status changed from Pending payment to Cancelled.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (115,90007804,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-28 23:30:15','2025-06-28 23:30:15','Stock hold of 60 minutes applied to: <br>- McAfee Internet Security - 1-Year / 3-Device (#90007229) &times; 2<br>- Malwarebytes Premium - 1-Year / 1-Device (#90007168) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (116,90007804,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-06-29 00:44:41','2025-06-29 00:44:41','Unpaid order cancelled - time limit reached. Order status changed from Pending payment to Cancelled.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (117,90007894,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-07-01 19:26:12','2025-07-01 19:26:12','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (#90007364) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (118,90007894,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-07-01 19:26:14','2025-07-01 19:26:14','Failed to process the payment. Please try again or contact the shop admin. [Error] Unknown error while connecting to PayPal. Status code: 0. PayPalGateway.php:513 [Error] Unknown error while connecting to PayPal. Status code: 0. OrderEndpoint.php:191 Order status changed from Pending payment to Failed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (119,90007894,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-07-01 19:26:21','2025-07-01 19:26:21','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (#90007364) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (120,90007894,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-07-01 19:26:32','2025-07-01 19:26:32','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (#90007364) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (121,90007894,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-07-01 19:29:35','2025-07-01 19:29:35','Stock hold of 60 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (#90007364) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (122,90007926,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-07-04 18:25:01','2025-07-04 18:25:01','PayPal transaction ID: 7HY32154WK4527704',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (123,90007926,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-07-04 18:25:02','2025-07-04 18:25:02','Stock levels reduced: McAfee Internet Security - 1-Year / 3-Device (#90007229) 34&rarr;33',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (124,90007926,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-07-04 18:25:02','2025-07-04 18:25:02','Awaiting payment. Order status changed from Pending payment to On hold.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (125,90007926,'Antiviruspoint.org','madav6310@gmail.com','','','2025-07-04 19:44:51','2025-07-04 19:44:51','Order status changed from On hold to Completed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (126,90007926,'Antiviruspoint.org','madav6310@gmail.com','','','2025-07-04 19:44:51','2025-07-04 19:44:51','Order details manually sent to customer.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (127,90007926,'Antiviruspoint.org','madav6310@gmail.com','','','2025-07-08 22:44:26','2025-07-08 22:44:26','Order details manually sent to customer.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (128,90007926,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-08-02 18:25:27','2025-08-02 18:25:27','Order status changed from Completed to Refunded.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (129,90007926,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-08-02 18:25:27','2025-08-02 18:25:27','PayPal transaction ID: 7HY32154WK4527704',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (130,90008190,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-09-03 18:14:37','2025-09-03 18:14:37','Stock hold of 10080 minutes applied to: <br>- Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (SKU-060) &times; 1',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (131,90008190,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-09-03 18:14:37','2025-09-03 18:14:37','Stock levels reduced: Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (SKU-060) 49&rarr;48',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (132,90008190,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-09-03 18:14:38','2025-09-03 18:14:38','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (133,90008190,'Antiviruspoint.org','madav6310@gmail.com','','','2025-09-03 18:16:02','2025-09-03 18:16:02','The order was paid by cash. Customer paid $19.95. The change due was $0.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (134,90008190,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-09-03 18:16:12','2025-09-03 18:16:12','Order status changed from Processing to Completed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (135,90008190,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-09-03 18:19:31','2025-09-03 18:19:31','Stock levels increased: Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe (SKU-060) 48&rarr;49',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `fqsi_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (136,90008190,'WooCommerce','woocommerce@antiviruspoint.org','','','2025-09-03 18:19:31','2025-09-03 18:19:31','Order status changed from Completed to Pending payment.',0,'1','WooCommerce','order_note',0,0);
