/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_woocommerce_order_items` (
  `order_item_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_item_name` text NOT NULL,
  `order_item_type` varchar(200) NOT NULL DEFAULT '',
  `order_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`order_item_id`),
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=179 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (1,'Norton 360 Standard - 1-Year / 1-Device - USA/Canada','line_item',90007023);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (2,'McAfee Total Protection - 1-Year / 3-Devices - USA/Canada','line_item',90007023);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (3,'McAfee Total Protection - 1-Year / 5-Devices - USA/Canada','line_item',90007025);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (4,'this is the product for test','line_item',90007086);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (5,'Norton 360 Standard - 1-Year / 1-Device - USA/Canada','line_item',90007181);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (6,'Watchdog Anti-Virus - 1-Year / 3-PC','line_item',90007265);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (7,'Malwarebytes Premium - 1-Year / 10-Device','line_item',90007439);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (8,'McAfee Internet Security - 1-Year / 3-Device','line_item',90007458);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (9,'Watchdog Anti-Malware - 3-Year / 1-PC','line_item',90007469);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (10,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007470);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (11,'McAfee Internet Security - 1-Year / 3-Device','line_item',90007474);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (12,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007474);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (13,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007476);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (14,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007477);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (15,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007478);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (16,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007481);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (17,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007487);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (18,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007491);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (19,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (20,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (21,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (22,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (23,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (24,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (25,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (26,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (27,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (28,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (29,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (30,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (31,'Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe','line_item',90007660);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (32,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (33,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (34,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (35,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (36,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (37,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (38,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (39,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (40,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (41,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (42,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (43,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (44,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (45,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (46,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (47,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (48,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (49,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (50,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (51,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (52,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (53,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (54,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (55,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (56,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (57,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (58,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (59,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (60,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (61,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (62,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (63,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (64,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (65,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (66,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (67,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (68,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (69,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (72,'Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe','line_item',90007732);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (73,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007732);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (75,'Norton 360 Standard - 1-Year / 1-Device - USA/Canada','line_item',90007744);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (76,'McAfee Total Protection - 1-Year / 10-Devices - Europe/UK','line_item',90007745);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (77,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (78,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (79,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (80,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (81,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (82,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (83,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (84,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (85,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (86,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (87,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (88,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (89,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (90,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (91,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (92,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (93,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (94,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (95,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (96,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (97,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (98,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (99,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (100,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (101,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (102,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (103,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (104,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (106,'Norton 360 Deluxe - 1-Year / 5-Device - UK/Europe','line_item',90007801);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (107,'McAfee Internet Security - 1-Year / 3-Device','line_item',90007804);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (108,'Malwarebytes Premium - 1-Year / 1-Device','line_item',90007804);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (109,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (110,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (111,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (112,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (116,'Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe','line_item',90007894);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (117,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (118,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (119,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (120,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (121,'McAfee Internet Security - 1-Year / 3-Device','line_item',90007926);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (122,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (123,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (124,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (125,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (126,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (127,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (128,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (129,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (130,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (131,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (132,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (133,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (134,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (135,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (136,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (137,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (138,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (139,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (140,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (141,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (142,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (143,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (144,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (145,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (146,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (147,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (148,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (149,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (150,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (151,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (152,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (153,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (154,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (155,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (156,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (157,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (158,'Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe','line_item',90008190);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (159,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (160,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (161,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (162,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (163,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (164,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (165,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (166,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (167,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (168,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (169,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (170,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (171,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (172,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (173,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (174,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (175,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (176,'Dummy Product Variation','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (177,'Dummy Product','line_item',0);
INSERT INTO `fqsi_woocommerce_order_items` (`order_item_id`, `order_item_name`, `order_item_type`, `order_id`) VALUES (178,'Dummy Product Variation','line_item',0);
