/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_terms` (
  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL DEFAULT '',
  `slug` varchar(200) NOT NULL DEFAULT '',
  `term_group` bigint(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`term_id`),
  KEY `slug` (`slug`(191)),
  KEY `name` (`name`(191))
) ENGINE=InnoDB AUTO_INCREMENT=168 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (1,'Uncategorized','uncategorized',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (2,'simple','simple',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (3,'grouped','grouped',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (4,'variable','variable',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (5,'external','external',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (6,'exclude-from-search','exclude-from-search',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (7,'exclude-from-catalog','exclude-from-catalog',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (8,'featured','featured',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (9,'outofstock','outofstock',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (10,'rated-1','rated-1',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (11,'rated-2','rated-2',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (12,'rated-3','rated-3',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (13,'rated-4','rated-4',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (14,'rated-5','rated-5',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (15,'VPN','vvpn',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (16,'News','news',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (17,'Games','games',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (18,'News','news',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (19,'Reviews','reviews',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (20,'Earth','earth',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (21,'Mobile','mobile',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (22,'Tech','tech',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (23,'Technology','technology',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (24,'Football','football',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (25,'Videos','videos',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (26,'Tags','tags',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (27,'WordPress','wordpress',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (47,'Valise','valise',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (50,'Main Menu','main-menu',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (51,'Top Menu','top-menu',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (53,'Category Menu','category-menu',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (54,'Footer Menu','footer-menu',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (55,'Useful Links','useful-links',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (56,'Footer Categories','footer-categories',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (57,'Hardware','hardware',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (58,'Software','software',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (59,'Android','androids',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (60,'AntiVirus','antivirus',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (61,'iOS','ios',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (62,'MacOS','mac',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (63,'Office Sofware','office',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (64,'Antimalware','antimalware',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (68,'Windows','windows',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (69,'2023','2023',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (70,'product','product',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (71,'secure','secure',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (72,'game','game',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (73,'vpn','vpn',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (74,'antivirus','antivirus',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (75,'norton','norton',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (76,'McAfee','mcafee',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (77,'Android','android',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (78,'secured','secured',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (79,'ios','ios',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (80,'security','security',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (81,'total-protection','total-protection',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (83,'Android','android',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (84,'ios','ios',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (85,'Mac','mac',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (86,'Windows','windows',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (88,'McAfee','mcafee',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (89,'Norton','norton',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (91,'Microsoft','microsoft',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (92,'ms office','ms-office',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (93,'software','software',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (94,'WatchDog','watchdog',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (95,'windows security','windows-security',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (96,'Anti-Virus','anti-virus',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (97,'Utility Tool','utility-tool',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (100,'Anti-malware','anti-malware',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (101,'Malewarebytes','malewarebytes',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (102,'MacOS','macos',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (103,'Mac OS','mac-os',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (107,'bundle','bundle',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (108,'header','header',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (109,'blocksy','blocksy',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (110,'Competition','competition',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (111,'Extreme','extreme',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (112,'Beige','beige',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (113,'Blue','blue',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (115,'Gray','gray',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (116,'Green','green',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (118,'Orange','orange',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (121,'White','white',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (122,'Yellow','yellow',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (123,'Standard Ticket Form','standard-ticket-form',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (124,'Email','email',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (125,'Chat','chat',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (126,'WordPress.org','wordpress-org',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (127,'Contact Form (Website)','contact-form-website',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (128,'Gravity Forms add-on','gravity-forms-add-on',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (129,'Twitter','twitter',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (130,'Twitter DM (direct message)','twitter-dm-direct-message',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (131,'Twitter Favorite','twitter-favorite',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (132,'Voicemail','voicemail',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (133,'Phone call (incoming)','phone-call-incoming',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (134,'Feedback Form','feedback-form',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (135,'Web service (API)','web-service-api',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (136,'Trigger or automation','trigger-or-automation',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (137,'Forum topic','forum-topic',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (138,'Facebook Post','facebook-post',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (139,'Facebook Message','facebook-message',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (141,'Other','other',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (143,'text','text',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (144,'after_paragraph','after_paragraph',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (145,'sample','sample',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (146,'message','message',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (147,'php','php',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (148,'everywhere','everywhere',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (149,'disable','disable',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (150,'comments','comments',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (151,'Essential','essential',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (152,'Statistics','statistics',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (153,'Marketing','marketing',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (154,'Comments','comments',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (155,'WooCommerce','woocommerce',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (156,'WP Consent API','wp-consent-api',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (157,'Google Tag Manager','google-tag-manager',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (158,'Google Analytics','google-analytics',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (159,'Facebook Pixel','facebook-pixel',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (160,'Google reCAPTCHA','google-recaptcha',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (161,'subscription','subscription',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (162,'Variable Subscription','variable-subscription',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (163,'ads','ads',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (165,'product','product',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (166,'dailyprompt','dailyprompt',0);
INSERT INTO `fqsi_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES (167,'dailyprompt-2043','dailyprompt-2043',0);
