/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_term_taxonomy` (
  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `term_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  `taxonomy` varchar(32) NOT NULL DEFAULT '',
  `description` longtext NOT NULL,
  `parent` bigint(20) unsigned NOT NULL DEFAULT 0,
  `count` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`term_taxonomy_id`),
  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),
  KEY `taxonomy` (`taxonomy`)
) ENGINE=InnoDB AUTO_INCREMENT=168 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (1,1,'category','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (2,2,'product_type','',0,57);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (3,3,'product_type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (4,4,'product_type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (5,5,'product_type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (6,6,'product_visibility','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (7,7,'product_visibility','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (8,8,'product_visibility','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (9,9,'product_visibility','',0,3);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (10,10,'product_visibility','',0,7);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (11,11,'product_visibility','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (12,12,'product_visibility','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (13,13,'product_visibility','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (14,14,'product_visibility','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (15,15,'product_cat','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (16,16,'category','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (17,17,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (18,18,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (19,19,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (20,20,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (21,21,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (22,22,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (23,23,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (24,24,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (25,25,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (26,26,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (27,27,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (47,47,'product_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (50,50,'nav_menu','',0,4);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (51,51,'nav_menu','',0,3);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (53,53,'nav_menu','',0,6);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (54,54,'nav_menu','',0,4);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (55,55,'nav_menu','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (56,56,'nav_menu','',0,6);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (57,57,'pa_product-type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (58,58,'pa_product-type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (59,59,'product_cat','',0,50);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (60,60,'product_cat','',0,36);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (61,61,'product_cat','',0,29);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (62,62,'product_cat','',0,22);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (63,63,'product_cat','',0,3);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (64,64,'product_cat','',60,22);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (68,68,'product_cat','',0,53);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (69,69,'product_tag','',0,3);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (70,70,'product_tag','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (71,71,'product_tag','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (72,72,'product_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (73,73,'product_tag','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (74,74,'product_tag','',0,4);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (75,75,'product_tag','',0,2);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (76,76,'product_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (77,77,'product_tag','',0,53);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (78,78,'product_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (79,79,'product_tag','',0,18);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (80,80,'product_tag','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (81,81,'product_tag','',0,2);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (83,83,'pa_platform','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (84,84,'pa_platform','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (85,85,'pa_platform','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (86,86,'pa_platform','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (88,88,'product_brand','',0,13);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (89,89,'product_brand','',0,14);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (91,91,'product_brand','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (92,92,'product_tag','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (93,93,'product_tag','',0,50);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (94,94,'product_brand','',0,21);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (95,95,'product_tag','',0,51);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (96,96,'product_tag','',0,33);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (97,97,'product_cat','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (100,100,'product_tag','',0,22);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (101,101,'product_brand','',0,7);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (102,102,'product_tag','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (103,103,'product_tag','',0,20);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (107,107,'product_type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (108,108,'elementor_library_type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (109,109,'wp_theme','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (110,110,'category','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (111,111,'category','',0,2);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (112,112,'pa_color','',0,4);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (113,113,'pa_color','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (115,115,'pa_color','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (116,116,'pa_color','',0,9);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (118,118,'pa_color','',0,7);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (121,121,'pa_color','',0,4);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (122,122,'pa_color','',0,5);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (123,123,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (124,124,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (125,125,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (126,126,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (127,127,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (128,128,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (129,129,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (130,130,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (131,131,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (132,132,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (133,133,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (134,134,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (135,135,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (136,136,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (137,137,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (138,138,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (139,139,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (141,141,'ticket_channel','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (143,143,'wpcode_type','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (144,144,'wpcode_location','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (145,145,'wpcode_tags','',0,2);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (146,146,'wpcode_tags','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (147,147,'wpcode_type','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (148,148,'wpcode_location','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (149,149,'wpcode_tags','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (150,150,'wpcode_tags','',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (151,151,'wpconsent_category','Essential cookies enable basic functions and are necessary for the proper function of the website.',0,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (152,152,'wpconsent_category','Statistics cookies collect information anonymously. This information helps us understand how visitors use our website.',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (153,153,'wpconsent_category','Marketing cookies are used to follow visitors to websites. The intention is to show ads that are relevant and engaging to the individual user.',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (154,154,'wpconsent_category','These cookies are needed for adding comments on this website.',151,3);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (155,155,'wpconsent_category','WooCommerce is a customizable eCommerce platform for building online stores using WordPress.',151,7);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (156,156,'wpconsent_category','WP Consent API is a plugin that standardizes the communication of accepted consent categories between plugins.',151,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (157,157,'wpconsent_category','Google Tag Manager simplifies the management of marketing tags on your website without code changes.',151,2);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (158,158,'wpconsent_category','Google Analytics is a powerful tool that tracks and analyzes website traffic for informed marketing decisions.',152,13);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (159,159,'wpconsent_category','Facebook Pixel is a web analytics service that tracks and reports website traffic.',153,3);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (160,160,'wpconsent_category','Google reCAPTCHA helps protect websites from spam and abuse by verifying user interactions through challenges.',151,1);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (161,161,'product_type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (162,162,'product_type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (163,163,'advanced_ads_groups','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (165,165,'elementor_library_type','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (166,166,'post_tag','',0,0);
INSERT INTO `fqsi_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES (167,167,'post_tag','',0,0);
