/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_wpcode_revisions` (
  `revision_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `snippet_id` bigint(20) NOT NULL,
  `revision_data` longtext NOT NULL,
  `author_id` bigint(20) NOT NULL,
  `created` datetime NOT NULL,
  `remote_id` varchar(20) NOT NULL,
  PRIMARY KEY (`revision_id`),
  KEY `snippet_id` (`snippet_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_wpcode_revisions` (`revision_id`, `snippet_id`, `revision_data`, `author_id`, `created`, `remote_id`) VALUES (1,0,'{\"ihaf_insert_header\":\"<!-- Google Tag Manager -->\\r\\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\\\\\'gtm.start\\\\\':\\r\\nnew Date().getTime(),event:\\\\\'gtm.js\\\\\'});var f=d.getElementsByTagName(s)[0],\\r\\nj=d.createElement(s),dl=l!=\\\\\'dataLayer\\\\\'?\\\\\'&l=\\\\\'+l:\\\\\'\\\\\';j.async=true;j.src=\\r\\n\\\\\'https:\\/\\/www.googletagmanager.com\\/gtm.js?id=\\\\\'+i+dl;f.parentNode.insertBefore(j,f);\\r\\n})(window,document,\\\\\'script\\\\\',\\\\\'dataLayer\\\\\',\\\\\'GTM-M8WRTQKW\\\\\');<\\/script>\\r\\n<!-- End Google Tag Manager -->\",\"ihaf_insert_footer\":\"\",\"ihaf_insert_body\":\"<!-- Google Tag Manager (noscript) -->\\r\\n<noscript><iframe src=\\\\\\\"https:\\/\\/www.googletagmanager.com\\/ns.html?id=GTM-M8WRTQKW\\\\\\\"\\r\\nheight=\\\\\\\"0\\\\\\\" width=\\\\\\\"0\\\\\\\" style=\\\\\\\"display:none;visibility:hidden\\\\\\\"><\\/iframe><\\/noscript>\\r\\n<!-- End Google Tag Manager (noscript) -->\"}',12,'2025-06-29 01:41:09','');
INSERT INTO `fqsi_wpcode_revisions` (`revision_id`, `snippet_id`, `revision_data`, `author_id`, `created`, `remote_id`) VALUES (2,0,'{\"ihaf_insert_header\":\"<!-- Google Tag Manager -->\\r\\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\\\\\'gtm.start\\\\\':\\r\\nnew Date().getTime(),event:\\\\\'gtm.js\\\\\'});var f=d.getElementsByTagName(s)[0],\\r\\nj=d.createElement(s),dl=l!=\\\\\'dataLayer\\\\\'?\\\\\'&l=\\\\\'+l:\\\\\'\\\\\';j.async=true;j.src=\\r\\n\\\\\'https:\\/\\/www.googletagmanager.com\\/gtm.js?id=\\\\\'+i+dl;f.parentNode.insertBefore(j,f);\\r\\n})(window,document,\\\\\'script\\\\\',\\\\\'dataLayer\\\\\',\\\\\'GTM-M8WRTQKW\\\\\');<\\/script>\\r\\n<!-- End Google Tag Manager -->\\r\\n\\r\\n<!-- Event snippet for Page view conversion page -->\\r\\n<script>\\r\\n  gtag(\\\\\'event\\\\\', \\\\\'conversion\\\\\', {\\\\\'send_to\\\\\': \\\\\'AW-17280021927\\/Iv1sCLSdxugaEKfr4K9A\\\\\'});\\r\\n<\\/script>\\r\\n\",\"ihaf_insert_footer\":\"\",\"ihaf_insert_body\":\"<!-- Google Tag Manager (noscript) -->\\r\\n<noscript><iframe src=\\\\\\\"https:\\/\\/www.googletagmanager.com\\/ns.html?id=GTM-M8WRTQKW\\\\\\\"\\r\\nheight=\\\\\\\"0\\\\\\\" width=\\\\\\\"0\\\\\\\" style=\\\\\\\"display:none;visibility:hidden\\\\\\\"><\\/iframe><\\/noscript>\\r\\n<!-- End Google Tag Manager (noscript) -->\\r\\n\\r\\n\\r\\n\\r\\n<script async src=\\\\\\\"https:\\/\\/pagead2.googlesyndication.com\\/pagead\\/js\\/adsbygoogle.js?client=ca-pub-5812544243310892\\\\\\\"\\r\\n     crossorigin=\\\\\\\"anonymous\\\\\\\"><\\/script>\"}',12,'2025-07-03 04:49:55','');
INSERT INTO `fqsi_wpcode_revisions` (`revision_id`, `snippet_id`, `revision_data`, `author_id`, `created`, `remote_id`) VALUES (3,0,'{\"ihaf_insert_header\":\"\\r\\n\",\"ihaf_insert_footer\":\"\",\"ihaf_insert_body\":\"\"}',12,'2025-08-23 06:29:03','');
INSERT INTO `fqsi_wpcode_revisions` (`revision_id`, `snippet_id`, `revision_data`, `author_id`, `created`, `remote_id`) VALUES (4,0,'{\"ihaf_insert_header\":\"\",\"ihaf_insert_footer\":\"<script type=\\\\\\\"text\\/javascript\\\\\\\">\\r\\n_linkedin_partner_id = \\\\\\\"7843642\\\\\\\";\\r\\nwindow._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];\\r\\nwindow._linkedin_data_partner_ids.push(_linkedin_partner_id);\\r\\n<\\/script><script type=\\\\\\\"text\\/javascript\\\\\\\">\\r\\n(function(l) {\\r\\nif (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};\\r\\nwindow.lintrk.q=[]}\\r\\nvar s = document.getElementsByTagName(\\\\\\\"script\\\\\\\")[0];\\r\\nvar b = document.createElement(\\\\\\\"script\\\\\\\");\\r\\nb.type = \\\\\\\"text\\/javascript\\\\\\\";b.async = true;\\r\\nb.src = \\\\\\\"https:\\/\\/snap.licdn.com\\/li.lms-analytics\\/insight.min.js\\\\\\\";\\r\\ns.parentNode.insertBefore(b, s);})(window.lintrk);\\r\\n<\\/script>\\r\\n<noscript>\\r\\n<img height=\\\\\\\"1\\\\\\\" width=\\\\\\\"1\\\\\\\" style=\\\\\\\"display:none;\\\\\\\" alt=\\\\\\\"\\\\\\\" src=\\\\\\\"https:\\/\\/px.ads.linkedin.com\\/collect\\/?pid=7843642&fmt=gif\\\\\\\" \\/>\\r\\n<\\/noscript>\",\"ihaf_insert_body\":\"\"}',12,'2025-09-03 10:21:41','');
