/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_wc_product_meta_lookup` (
  `product_id` bigint(20) NOT NULL,
  `sku` varchar(100) DEFAULT '',
  `global_unique_id` varchar(100) DEFAULT '',
  `virtual` tinyint(1) DEFAULT 0,
  `downloadable` tinyint(1) DEFAULT 0,
  `min_price` decimal(19,4) DEFAULT NULL,
  `max_price` decimal(19,4) DEFAULT NULL,
  `onsale` tinyint(1) DEFAULT 0,
  `stock_quantity` double DEFAULT NULL,
  `stock_status` varchar(100) DEFAULT 'instock',
  `rating_count` bigint(20) DEFAULT 0,
  `average_rating` decimal(3,2) DEFAULT 0.00,
  `total_sales` bigint(20) DEFAULT 0,
  `tax_status` varchar(100) DEFAULT 'taxable',
  `tax_class` varchar(100) DEFAULT '',
  PRIMARY KEY (`product_id`),
  KEY `virtual` (`virtual`),
  KEY `downloadable` (`downloadable`),
  KEY `stock_status` (`stock_status`),
  KEY `stock_quantity` (`stock_quantity`),
  KEY `onsale` (`onsale`),
  KEY `min_max_price` (`min_price`,`max_price`),
  KEY `sku` (`sku`(50))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (4024,'','',0,0,790.0000,790.0000,0,NULL,'instock',1,4.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006936,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006937,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006938,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006939,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006940,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006941,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006942,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006943,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006944,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006945,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006946,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006947,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006948,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006949,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006950,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006955,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006956,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006957,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006958,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006959,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006960,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006961,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006962,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006963,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006964,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006965,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006966,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006967,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006968,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006969,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006971,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006972,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006973,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006974,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006975,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006976,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006977,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006978,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006979,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006980,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006981,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006982,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006983,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006984,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006985,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006987,'SKU-001','',1,1,43.5000,43.5000,1,9,'instock',0,0.00,3,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006988,'','',1,1,239.9700,239.9700,0,8,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006989,'SKU-002','',1,1,200.0000,200.0000,1,9,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006990,'','',1,1,58.5000,58.5000,0,0,'outofstock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006991,'','',1,1,160.5000,160.5000,0,9,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006992,'SKU-003','',1,1,43.0000,43.0000,1,0,'outofstock',1,1.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006993,'SKU-004','',1,1,18.0000,18.0000,0,0,'outofstock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006994,'SKU-005','',1,1,49.9900,49.9900,1,0,'outofstock',0,0.00,1,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006995,'','',1,1,15.0000,15.0000,1,23,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006996,'','',1,1,24.0000,24.0000,1,14,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006997,'SKU-006','',1,1,40.0000,40.0000,1,0,'outofstock',0,0.00,1,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006998,'','',1,1,51.0000,51.0000,1,8,'instock',0,0.00,1,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90006999,'SKU-007','',1,1,30.0000,30.0000,1,0,'outofstock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007000,'','',1,1,40.5000,40.5000,1,8,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007001,'SKU-008','',1,1,51.0000,51.0000,1,0,'outofstock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007003,'','',0,0,10.0000,10.0000,1,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007085,'','',0,0,100.0000,100.0000,1,NULL,'instock',0,0.00,1,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007088,'SKU-009','',1,1,29.0000,29.0000,1,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007090,'SKU-010','',1,1,25.0000,25.0000,1,NULL,'instock',1,1.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007092,'SKU-011','',1,1,59.9500,59.9500,1,19,'instock',0,0.00,1,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007094,'SKU-012','',1,1,79.9500,79.9500,1,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007096,'SKU-013','',1,1,59.9500,59.9500,1,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007097,'SKU-014','',1,1,79.9500,79.9500,1,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007098,'SKU-015','',1,1,99.9500,99.9500,1,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007100,'SKU-016','',1,1,19.9900,19.9900,1,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007105,'SKU-017','',1,1,79.9500,79.9500,1,20,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007107,'SKU-018','',1,1,29.9900,29.9900,1,34,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007110,'SKU-019','',1,1,39.9900,39.9900,1,15,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007111,'SKU-020','',1,1,99.9500,99.9500,1,25,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007113,'SKU-021','',1,1,79.9500,79.9500,1,23,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007114,'SKU-022','',1,1,119.9500,119.9500,1,30,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007122,'SKU-023','',1,1,29.9900,29.9900,1,43,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007127,'SKU-024','',1,1,39.9900,39.9900,1,12,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007133,'SKU-025','',1,1,49.9900,49.9900,1,43,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007143,'SKU-026','',1,1,39.9900,39.9900,1,44,'instock',0,0.00,1,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007145,'SKU-027','',1,1,49.9900,49.9900,1,54,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007153,'SKU-028','',1,1,59.9900,59.9900,1,53,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007158,'SKU-029','',1,1,99.9900,99.9900,1,44,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007159,'SKU-030','',1,1,49.9900,49.9900,1,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007160,'SKU-031','',1,1,299.9900,299.9900,1,20,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007162,'','',0,0,100.0000,100.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007163,'SKU-032','199284707566',1,1,99.9900,99.9900,0,45,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007166,'SKU-033','',1,1,104.9900,104.9900,1,34,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007168,'SKU-034','',1,1,39.9900,39.9900,1,54,'instock',1,1.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007185,'SKU-035','',1,1,109.9900,109.9900,1,53,'instock',0,0.00,1,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007186,'SKU-036','',1,1,49.9900,49.9900,1,32,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007188,'SKU-037','',1,1,49.9900,49.9900,1,45,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007189,'SKU-038','',1,1,49.9900,49.9900,1,13,'instock',1,1.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007218,'SKU-039','',1,1,44.9900,44.9900,1,18,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007221,'SKU-040','',1,1,99.9900,99.9900,1,25,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007226,'SKU-041','',1,1,14.9500,14.9500,1,29,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007229,'SKU-042','',1,1,17.9500,17.9500,1,33,'instock',0,0.00,2,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007230,'SKU-043','',1,1,19.9500,19.9500,1,40,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007231,'SKU-044','',1,1,24.9500,24.9500,1,45,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007232,'SKU-045','',1,1,79.9500,79.9500,1,50,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007233,'SKU-046','',1,0,29.9900,29.9900,1,27,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007250,'SKU-047','',1,1,59.9900,59.9900,1,40,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007264,'SKU-048','',1,1,84.9900,84.9900,1,40,'instock',1,1.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007266,'SKU-049','',1,1,89.9900,89.9900,1,50,'instock',1,1.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007267,'SKU-050','',1,1,99.9900,99.9900,1,50,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007279,'SKU-051','',1,1,84.9900,84.9900,1,56,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007297,'SKU-052','',1,1,19.9500,19.9500,1,20,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007300,'SKU-053','',1,1,94.9900,94.9900,1,30,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007302,'SKU-054','',1,1,99.9900,99.9900,1,30,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007306,'SKU-055','',1,1,179.9900,179.9900,1,50,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007309,'SKU-056','',1,1,124.9900,124.9900,1,33,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007311,'SKU-057','',1,1,99.9900,99.9900,1,30,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007314,'SKU-058','',1,1,79.9900,79.9900,1,40,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007339,'SKU-059','',1,1,29.9500,29.9500,1,40,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007364,'SKU-060','',1,1,19.9500,19.9500,1,49,'instock',1,1.00,2,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007366,'AVP-7X3G9L5T','07-4589-2365-1247',1,1,1.9500,1.9500,1,45,'instock',0,0.00,10,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007499,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007500,'','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
INSERT INTO `fqsi_wc_product_meta_lookup` (`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`) VALUES (90007618,'SKU-061','',0,0,0.0000,0.0000,0,NULL,'instock',0,0.00,0,'taxable','');
