/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_zbs_contacts` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `zbs_site` int(11) DEFAULT NULL,
  `zbs_team` int(11) DEFAULT NULL,
  `zbs_owner` int(11) NOT NULL,
  `zbsc_status` varchar(100) DEFAULT NULL,
  `zbsc_email` varchar(200) DEFAULT NULL,
  `zbsc_prefix` varchar(30) DEFAULT NULL,
  `zbsc_fname` varchar(100) DEFAULT NULL,
  `zbsc_lname` varchar(100) DEFAULT NULL,
  `zbsc_addr1` varchar(200) DEFAULT NULL,
  `zbsc_addr2` varchar(200) DEFAULT NULL,
  `zbsc_city` varchar(200) DEFAULT NULL,
  `zbsc_county` varchar(200) DEFAULT NULL,
  `zbsc_country` varchar(200) DEFAULT NULL,
  `zbsc_postcode` varchar(50) DEFAULT NULL,
  `zbsc_secaddr1` varchar(200) DEFAULT NULL,
  `zbsc_secaddr2` varchar(200) DEFAULT NULL,
  `zbsc_seccity` varchar(200) DEFAULT NULL,
  `zbsc_seccounty` varchar(200) DEFAULT NULL,
  `zbsc_seccountry` varchar(200) DEFAULT NULL,
  `zbsc_secpostcode` varchar(50) DEFAULT NULL,
  `zbsc_hometel` varchar(40) DEFAULT NULL,
  `zbsc_worktel` varchar(40) DEFAULT NULL,
  `zbsc_mobtel` varchar(40) DEFAULT NULL,
  `zbsc_wpid` int(11) DEFAULT NULL,
  `zbsc_avatar` varchar(300) DEFAULT NULL,
  `zbsc_tw` varchar(100) DEFAULT NULL,
  `zbsc_li` varchar(300) DEFAULT NULL,
  `zbsc_fb` varchar(200) DEFAULT NULL,
  `zbsc_created` int(14) NOT NULL,
  `zbsc_lastupdated` int(14) NOT NULL,
  `zbsc_lastcontacted` int(14) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `zbsc_email` (`zbsc_email`,`zbsc_wpid`),
  KEY `zbsc_status` (`zbsc_status`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (1,1,1,-1,'Lead','divyanshu.tiwari@thecodeyogi.com','','Divyanshu','Tiwari','G 43 Noida sector 3','','Noida','UP','IN','201301','','','','','US','','9548254043','','',-1,'','','','',1737041830,1784565256,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (2,1,1,-1,'Lead','anuraghandique.dev@gmail.com','','Anurag','Handique','16','Rg Recidency','Test','AS','IN','201301','','','','','','','6900864982','','',1,'','','','',1737365723,1784565256,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (3,1,1,-1,'Lead','Mandrewc@comcast.net','','Michael','Crose','7301 33RD Way NE','','Lacey','WA','US','98516-1426','','','','','','','3609152802','','',-1,'','','','',1737473008,1784565258,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (4,1,1,-1,'Lead','frankd@gmail.com','','frank','test','new york','','new york','CA','US','48006','','','','','','','8175539807','','',-1,'','','','',1738083667,1784565258,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (5,1,1,-1,'Lead','neor@thecodeyogi.com','','Laurel S','Crose','7301 33rd Way NE','','Lacey','WA','US','98516','','','','','','','3608781682','','',-1,'','','','',1739369429,1784565256,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (6,1,1,-1,'Lead','infinity@antiviruspoint.org','','Anurag','Handique','Sector 120 Main Rd','Rg Recidency','Noida','UP','IN','201307','','','','','','','+916900864982','','',1,'','','','',1739441548,1784565258,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (7,1,1,-1,'Lead','rajnish.k@thecodeyogi.com','','raj','raj','[ouh9o[kmp','','o0uplk[0olk','UP','IN','201301','','','','','','','6900864982','','',-1,'','','','',1739531026,1784565256,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (8,1,1,-1,'Lead','info@thecodeyogi.com','','Anurag','Handique','Gohain Gaon','','Golaghat','AS','IN','785601','','','','','','','+916900864982','','',-1,'','','','',1739534419,1784565256,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (9,1,1,-1,'Lead','hyogi067@gmail.com','','Hemendra','Test','dettorid','Kardhani mode','michagan','MI','US','48006','','','','','','','+19874352134','','',-1,'','','','',1750700049,1784565256,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (10,1,1,-1,'Lead','madav6310@gmail.com','','madav6310','Saingar','4512 North Saginaw Road','APT 402','Midland','MI','US','45008','','','','','','','+13142394102','','',12,'','','','',1751051105,1784565258,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (11,1,1,-1,'Lead','Lokendra07@outlook.com','','LOKENDRA','SAINGAR','279 , rajput basti saingarpura khurd','','karauli','CO','US','45008','','','','','','','+132343434','','',16,'','','','',1751051883,1784565258,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (12,1,1,-1,'Lead','mohu3001@gmail.com','','LOKENDRA','Test','61 uttam nagar behind power house','Kardhani mode','Jaipur','MI','US','48069','','','','','','','+917877180969','','',-1,'','','','',1751397972,1784565257,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (13,1,1,-1,'Lead','tomvancaster@yahoo.com','','Thomas','VanCaster','','','','','US','','','','','','','','2628182869','','',-1,'','','','',1751653499,1784565257,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (15,1,1,-1,'Lead','astitva@gmail.com','','Astitva','Pathak','Kailashpuri Road Tikrapara near Sahu Murti Bhandar','','Raipur','CA','US','90001','','','','','','','7389522364','','',-1,'','','','',1756923276,1784565257,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (16,1,1,-1,'Lead','Loken07@yahoo.com','','ChatGPT','Helpe','','','','','','','','','','','','','','','',26,'','','','',1757461615,1784565258,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (17,1,1,-1,'Lead','loken9350@gmail.com','','ChatGPT','Helper','','','','','','','','','','','','','','','',27,'','','','',1757462743,1784565258,-1);
INSERT INTO `fqsi_zbs_contacts` (`ID`, `zbs_site`, `zbs_team`, `zbs_owner`, `zbsc_status`, `zbsc_email`, `zbsc_prefix`, `zbsc_fname`, `zbsc_lname`, `zbsc_addr1`, `zbsc_addr2`, `zbsc_city`, `zbsc_county`, `zbsc_country`, `zbsc_postcode`, `zbsc_secaddr1`, `zbsc_secaddr2`, `zbsc_seccity`, `zbsc_seccounty`, `zbsc_seccountry`, `zbsc_secpostcode`, `zbsc_hometel`, `zbsc_worktel`, `zbsc_mobtel`, `zbsc_wpid`, `zbsc_avatar`, `zbsc_tw`, `zbsc_li`, `zbsc_fb`, `zbsc_created`, `zbsc_lastupdated`, `zbsc_lastcontacted`) VALUES (18,1,1,-1,'Lead','xdevoty@gmail.com','','Chagpt','User','','','','','','','','','','','','','','','',29,'','','','',1757475525,1784565258,-1);
