/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_gla_merchant_issues` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `product_id` bigint(20) NOT NULL,
  `issue` varchar(200) NOT NULL,
  `code` varchar(100) NOT NULL,
  `severity` varchar(20) NOT NULL DEFAULT 'warning',
  `product` varchar(100) NOT NULL,
  `action` text NOT NULL,
  `action_url` varchar(1024) NOT NULL,
  `applicable_countries` text NOT NULL,
  `source` varchar(10) NOT NULL DEFAULT 'mc',
  `type` varchar(10) NOT NULL DEFAULT 'product',
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2254 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2198,0,'Account suspended due to policy violation: Misrepresentation','misrepresentation_of_self_or_products_unacceptable_business_practice_policy','critical','All products','','https://support.google.com/merchants/answer/6150127','{\"0\":\"CA\",\"7\":\"US\"}','mc','account','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2199,0,'The Google Product Feed plugin may cause conflicts or unexpected results.','incompatible_google_product_feed','error','All products','Deactivate the Google Product Feed plugin from your store','https://developers.google.com/shopping-content/guides/best-practices#do-not-use-api-and-feeds','','filter','account','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2200,90006987,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Standard - 1-Year / 1-Device - USA/Canada','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2201,90006989,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Deluxe with LifeLock Select - 1-Year / 5-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2202,90007088,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Microsoft Office Home 2024 - 1-PC/Mac','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2203,90007090,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 1-Year / 1-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2204,90007092,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 1-Year / 3-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2205,90007094,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 1-Year / 5-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2206,90007096,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 2-Year / 1-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2207,90007097,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 2-Year / 3-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2208,90007098,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 2-Year / 5-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2209,90007100,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 1-Year / 1-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2210,90007105,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 3-Year / 1-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2211,90007107,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 1-Year / 3-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2212,90007110,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 1-Year / 5-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2213,90007111,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 3-Year / 3-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2214,90007113,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 1-Year / 10-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2215,90007114,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Virus - 3-Year / 5-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2216,90007122,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 2-Year / 1-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2217,90007127,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 2-Year / 3-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2218,90007133,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 2-Year / 5-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2219,90007143,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 3-Year / 1-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2220,90007145,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 3-Year / 3-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2221,90007153,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - 3-Year / 5-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2222,90007158,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - Lifetime of Device / 1-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2223,90007159,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2224,90007160,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Watchdog Anti-Malware - Lifetime of Device / 3-PC','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2225,90007163,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Malwarebytes Premium + Privacy VPN Bundle - 1-Year / 2-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2226,90007166,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Malwarebytes Premium + Privacy VPN Bundle - 1-Year / 4-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2227,90007168,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Malwarebytes Premium - 1-Year / 1-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2228,90007185,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Malwarebytes Premium - 1-Year / 10-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2229,90007186,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Malwarebytes Premium - 1-Year / 3-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2230,90007188,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Malwarebytes Premium - 1-Year / 5-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2231,90007189,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Malwarebytes Premium for Mac - 1-Year / 1-Mac','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2232,90007218,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee AntiVirus - 1-Year / 1-PC - TSS','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2233,90007221,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee AntiVirus - 3-Year / 1-PC - TSS','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2234,90007226,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Internet Security - 1-Year / 1-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2235,90007229,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Internet Security - 1-Year / 3-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2236,90007230,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Internet Security - 1-Year / 5-Device','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2237,90007231,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Internet Security - 1-Year / 10-Devices','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2238,90007232,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Internet Security - 3-Year / 1-Device - TSS','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2239,90007233,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Mobile Security - 1-Year / 1-Android','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2240,90007250,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Total Protection - 1-Year / 1-Device - Europe/UK','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2241,90007264,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Total Protection - 1-Year / 3-Devices - Europe/UK','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2242,90007266,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Total Protection - 1-Year / 5-Devices - Europe/UK','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2243,90007267,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','McAfee Total Protection - 1-Year / 10-Devices - Europe/UK','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2244,90007279,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Standard - 1-Year / 1-Device - USA/Canada','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2245,90007297,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Standard - 1-Year / 1-Device - Canada','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2246,90007300,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Deluxe - 1-Year / 3-Device - USA/Canada','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2247,90007302,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Deluxe - 1-Year / 5-Device - USA/Canada','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2248,90007306,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Deluxe with LifeLock Select - 1-Year / 5-Device - USA','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2249,90007309,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Premium - 1-Year / 10-Device - USA/Canada','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2250,90007311,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 for Gamers - 1-Year / 3-Devices - Global','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2251,90007314,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton Secure VPN - 1-Year / 5-Device - USA/Canada','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2252,90007339,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Standard - 1-Year / 1-Device - UK/Europe','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
INSERT INTO `fqsi_gla_merchant_issues` (`id`, `product_id`, `issue`, `code`, `severity`, `product`, `action`, `action_url`, `applicable_countries`, `source`, `type`, `created_at`) VALUES (2253,90007364,'Suspended account for policy violation','policy_enforcement_account_disapproval','disapproved','Norton 360 Deluxe - 1-Year / 3-Device - UK/Europe','Remove products that violate our policies, or request a manual review','https://support.google.com/merchants/answer/2948694','[\"CA\",\"CA\",\"US\",\"US\"]','mc','product','2025-09-09 18:02:55');
