/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fqsi_wc_orders_meta` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) unsigned DEFAULT NULL,
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `order_id_meta_key_meta_value` (`order_id`,`meta_key`(100),`meta_value`(82)),
  KEY `meta_key_value` (`meta_key`(50),`meta_value`(20))
) ENGINE=InnoDB AUTO_INCREMENT=509 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (1,90007023,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (2,90007023,'_billing_address_index','Divyanshu Tiwari thecodeyogi G 43 Noida sector 3  Noida UP 201301 IN divyanshu.tiwari@thecodeyogi.com 9548254043');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (3,90007023,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (4,90007023,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (5,90007023,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/cart/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (6,90007023,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (7,90007023,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/cart/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (8,90007023,'_wc_order_attribution_session_start_time','2025-01-16 14:41:06');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (9,90007023,'_wc_order_attribution_session_pages','22');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (10,90007023,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (11,90007023,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (12,90007023,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (13,90007025,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (14,90007025,'_billing_address_index','Divyanshu Tiwari thecodeyogi G 43 Noida sector 3  Noida UP 201301 IN divyanshu.tiwari@thecodeyogi.com 9548254043');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (15,90007025,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (16,90007025,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (17,90007025,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (18,90007025,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (19,90007025,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (20,90007025,'_wc_order_attribution_session_start_time','2025-01-17 05:00:44');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (21,90007025,'_wc_order_attribution_session_pages','15');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (22,90007025,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (23,90007025,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (24,90007025,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (25,90007086,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (26,90007086,'_billing_address_index','Divyanshu Tiwari thecodeyogi G 43 Noida sector 3  Noida UP 201301 IN divyanshu.tiwari@thecodeyogi.com 9548254043');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (27,90007086,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (28,90007086,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (29,90007086,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (30,90007086,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (31,90007086,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (32,90007086,'_wc_order_attribution_session_start_time','2025-01-17 05:00:44');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (33,90007086,'_wc_order_attribution_session_pages','7');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (34,90007086,'_wc_order_attribution_session_count','3');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (35,90007086,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (36,90007086,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (37,90007181,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (38,90007181,'_billing_address_index','Divyanshu Tiwari thecodeyogi G 43 Noida sector 3  Noida UP 201301 IN divyanshu.tiwari@thecodeyogi.com 9548254043');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (39,90007181,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (40,90007181,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (41,90007181,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (42,90007181,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (43,90007181,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (44,90007181,'_wc_order_attribution_session_start_time','2025-01-17 05:00:44');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (45,90007181,'_wc_order_attribution_session_pages','37');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (46,90007181,'_wc_order_attribution_session_count','4');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (47,90007181,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (48,90007181,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (50,90007181,'lmfwc_order_complete','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (51,90007265,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (52,90007265,'_billing_address_index','Anurag Handique KNACKHELP CONSULTING SERVICES PRIVATE LIMITED Sector 120 Main Rd Rg Recidency Noida UP 201307 IN anuraghandique.dev@gmail.com +916900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (53,90007265,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (54,90007265,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (55,90007265,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (56,90007265,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (57,90007265,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (58,90007265,'_wc_order_attribution_session_start_time','2025-01-20 05:06:49');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (59,90007265,'_wc_order_attribution_session_pages','9');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (60,90007265,'_wc_order_attribution_session_count','3');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (61,90007265,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (62,90007265,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (63,90007439,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (64,90007439,'_billing_address_index','Michael Crose  7301 33RD Way NE  Lacey WA 98516-1426 US Mandrewc@comcast.net 3609152802');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (65,90007439,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (66,90007439,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (67,90007439,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (68,90007439,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (69,90007439,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (70,90007439,'_wc_order_attribution_session_start_time','2025-01-21 15:15:53');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (71,90007439,'_wc_order_attribution_session_pages','12');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (72,90007439,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (73,90007439,'_wc_order_attribution_user_agent','Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (74,90007439,'_wc_order_attribution_device_type','Mobile');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (75,90007458,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (76,90007458,'_billing_address_index','frank test  new york  new york CA 48006 US frankd@gmail.com 8175539807');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (77,90007458,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (78,90007458,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (79,90007458,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (80,90007458,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (81,90007458,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (82,90007458,'_wc_order_attribution_session_start_time','2025-01-28 16:27:56');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (83,90007458,'_wc_order_attribution_session_pages','8');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (84,90007458,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (85,90007458,'_wc_order_attribution_user_agent','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (86,90007458,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (87,90007469,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (88,90007469,'_billing_address_index','Laurel S Crose  7301 33rd Way NE  Lacey WA 98516 US neor@thecodeyogi.com 3608781682');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (89,90007469,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (90,90007469,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (91,90007469,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (92,90007469,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (93,90007469,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (94,90007469,'_wc_order_attribution_session_start_time','2025-02-12 11:44:42');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (95,90007469,'_wc_order_attribution_session_pages','11');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (96,90007469,'_wc_order_attribution_session_count','2');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (97,90007469,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (98,90007469,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (99,90007469,'_payment_method_id','pm_1Qrge32HeNMDbl9AtEtKX0X9');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (100,90007469,'_stripe_customer_id','cus_RlD4T2hLxrIpXP');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (101,90007469,'_wcpay_mode','prod');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (102,90007469,'_intent_id','pi_3Qrge42HeNMDbl9A1sc5Wky4');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (103,90007469,'_charge_id','ch_3Qrge42HeNMDbl9A1vSInXvW');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (104,90007469,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (105,90007469,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (106,90007469,'_wcpay_payment_transaction_id','txn_3Qrge42HeNMDbl9A1YgIw7t0');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (107,90007469,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (108,90007469,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (109,90007469,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (110,90007469,'_wcpay_transaction_fee','1.46');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (111,90007469,'last4','3108');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (112,90007469,'_card_brand','mastercard');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (113,90007469,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (114,90007469,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (116,90007470,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (117,90007470,'_billing_address_index','Anurag Handique  Gohain Gaon  Golaghat AS 785601 IN anuraghandique.dev@gmail.com +916900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (118,90007470,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (119,90007470,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (120,90007470,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (121,90007470,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (122,90007470,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (123,90007470,'_wc_order_attribution_session_start_time','2025-02-12 10:34:57');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (124,90007470,'_wc_order_attribution_session_pages','6');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (125,90007470,'_wc_order_attribution_session_count','2');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (126,90007470,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (127,90007470,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (128,90007470,'_payment_method_id','pm_1Qrh2z2HeNMDbl9AdpA6lLbV');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (129,90007470,'_stripe_customer_id','cus_RlDTT3o0WEcmRx');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (130,90007470,'_wcpay_mode','test');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (131,90007470,'_intent_id','pi_3Qrh302HeNMDbl9A19xCo7Hp');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (132,90007470,'_charge_id','ch_3Qrh302HeNMDbl9A16RLR67A');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (133,90007470,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (134,90007470,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (135,90007470,'_wcpay_payment_transaction_id','txn_3Qrh302HeNMDbl9A1zTpoWZn');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (136,90007470,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (137,90007470,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (138,90007470,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (139,90007470,'_wcpay_transaction_fee','1.02');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (140,90007470,'_wcpay_transaction_fee','1.02');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (141,90007470,'last4','4242');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (142,90007470,'_card_brand','visa');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (143,90007470,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (144,90007474,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (145,90007474,'_billing_address_index','Anurag Handique KNACKHELP CONSULTING SERVICES PRIVATE LIMITED Sector 120 Main Rd Rg Recidency Noida UP 201307 IN anuraghandique.dev@gmail.com +916900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (146,90007474,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (147,90007474,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (148,90007474,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/edit.php?post_type=product&page=lmfwc_licenses');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (149,90007474,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (150,90007474,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (151,90007474,'_wc_order_attribution_session_start_time','2025-02-13 09:26:13');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (152,90007474,'_wc_order_attribution_session_pages','11');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (153,90007474,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (154,90007474,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (155,90007474,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (156,90007474,'_payment_method_id','pm_1QrzPJ2HeNMDbl9AXhI4Iong');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (157,90007474,'_stripe_customer_id','cus_RlWSh8SMGvF5J2');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (158,90007474,'_wcpay_mode','test');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (159,90007474,'_intent_id','pi_3QrzPJ2HeNMDbl9A0bejRXh2');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (160,90007474,'_charge_id','ch_3QrzPJ2HeNMDbl9A0DK4E8IB');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (161,90007474,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (162,90007474,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (163,90007474,'_wcpay_payment_transaction_id','txn_3QrzPJ2HeNMDbl9A010T9Erc');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (164,90007474,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (165,90007474,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (166,90007474,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (167,90007474,'_wcpay_transaction_fee','2.47');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (168,90007474,'_wcpay_transaction_fee','2.47');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (169,90007474,'last4','4242');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (170,90007474,'_card_brand','visa');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (171,90007474,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (172,90007476,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (173,90007476,'_billing_address_index','Anurag Handique  Gohain Gaon  Golaghat AS 785601 IN anuraghandique.dev@gmail.com +916900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (174,90007476,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (175,90007476,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (176,90007476,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (177,90007476,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/product/norton-360-deluxe-1-year-5-device-uk-europe/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (178,90007476,'_wc_order_attribution_session_start_time','2025-02-13 09:49:40');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (179,90007476,'_wc_order_attribution_session_pages','29');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (180,90007476,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (181,90007476,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (182,90007476,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (183,90007476,'_payment_method_id','pm_1QrzXT2HeNMDbl9At42Fu0M3');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (184,90007476,'_stripe_customer_id','cus_RlDTT3o0WEcmRx');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (185,90007476,'_wcpay_mode','test');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (186,90007476,'_intent_id','pi_3QrzXT2HeNMDbl9A1MVaGEA0');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (187,90007476,'_charge_id','ch_3QrzXT2HeNMDbl9A1Mzl1ojS');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (188,90007476,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (189,90007476,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (190,90007476,'_wcpay_payment_transaction_id','txn_3QrzXT2HeNMDbl9A13DRtqLL');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (191,90007476,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (192,90007476,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (193,90007476,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (194,90007476,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (195,90007476,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (196,90007476,'last4','4242');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (197,90007476,'_card_brand','visa');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (198,90007476,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (199,90007477,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (200,90007477,'_billing_address_index','Anurag Handique  Gohain Gaon  Golaghat AS 785601 IN anuraghandique.dev@gmail.com +916900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (201,90007477,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (202,90007477,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (203,90007477,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (204,90007477,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/product/norton-360-deluxe-1-year-5-device-uk-europe/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (205,90007477,'_wc_order_attribution_session_start_time','2025-02-13 09:49:40');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (206,90007477,'_wc_order_attribution_session_pages','36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (207,90007477,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (208,90007477,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (209,90007477,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (210,90007477,'_payment_method_id','pm_1QrzcA2HeNMDbl9AowndMvmv');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (211,90007477,'_stripe_customer_id','cus_RlDTT3o0WEcmRx');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (212,90007477,'_wcpay_mode','test');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (213,90007477,'_intent_id','pi_3QrzcA2HeNMDbl9A0FhK0FfV');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (214,90007477,'_charge_id','ch_3QrzcA2HeNMDbl9A0rEuzgHx');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (215,90007477,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (216,90007477,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (217,90007477,'_wcpay_payment_transaction_id','txn_3QrzcA2HeNMDbl9A0CQ7J7Po');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (218,90007477,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (219,90007477,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (220,90007477,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (221,90007477,'lmfwc_order_complete','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (222,90007477,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (223,90007477,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (224,90007477,'last4','4242');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (225,90007477,'_card_brand','visa');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (226,90007477,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (227,90007478,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (228,90007478,'_billing_address_index','Anurag Handique  Gohain Gaon  Golaghat AS 785601 IN anuraghandique.dev@gmail.com +916900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (229,90007478,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (230,90007478,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (231,90007478,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (232,90007478,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/product/norton-360-deluxe-1-year-5-device-uk-europe/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (233,90007478,'_wc_order_attribution_session_start_time','2025-02-13 09:49:40');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (234,90007478,'_wc_order_attribution_session_pages','44');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (235,90007478,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (236,90007478,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (237,90007478,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (238,90007478,'_payment_method_id','pm_1Qrzrd2HeNMDbl9AcjLgAvAh');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (239,90007478,'_stripe_customer_id','cus_RlDTT3o0WEcmRx');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (240,90007478,'_wcpay_mode','test');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (241,90007478,'_intent_id','pi_3Qrzrd2HeNMDbl9A0T50L950');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (242,90007478,'_charge_id','ch_3Qrzrd2HeNMDbl9A0daLc5k3');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (243,90007478,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (244,90007478,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (245,90007478,'_wcpay_payment_transaction_id','txn_3Qrzrd2HeNMDbl9A0MGaSxOE');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (246,90007478,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (247,90007478,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (248,90007478,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (249,90007478,'lmfwc_order_complete','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (250,90007478,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (251,90007478,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (252,90007478,'last4','4242');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (253,90007478,'_card_brand','visa');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (254,90007478,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (255,90007481,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (256,90007481,'_billing_address_index','raj raj thecodeyogi [ouh9o[kmp  o0uplk[0olk UP 201301 IN rajnish.k@thecodeyogi.com 6900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (257,90007481,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (258,90007481,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (259,90007481,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (260,90007481,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (261,90007481,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (262,90007481,'_wc_order_attribution_session_start_time','2025-02-14 10:29:08');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (263,90007481,'_wc_order_attribution_session_pages','10');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (264,90007481,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (265,90007481,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (266,90007481,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (267,90007481,'_payment_method_id','pm_1QsMgU2HeNMDbl9AsLmu4lZi');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (268,90007481,'_stripe_customer_id','cus_RluVaG2vG7Xcbd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (269,90007481,'_wcpay_mode','test');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (270,90007481,'_intent_id','pi_3QsMgU2HeNMDbl9A0y3LbJ5u');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (271,90007481,'_charge_id','ch_3QsMgU2HeNMDbl9A0meRadOo');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (272,90007481,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (273,90007481,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (274,90007481,'_wcpay_payment_transaction_id','txn_3QsMgU2HeNMDbl9A0hK5w4FE');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (275,90007481,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (276,90007481,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (277,90007481,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (278,90007481,'lmfwc_order_complete','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (279,90007481,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (280,90007481,'last4','4242');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (281,90007481,'_card_brand','visa');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (282,90007481,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (283,90007487,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (284,90007487,'_billing_address_index','Anurag Handique  Gohain Gaon  Golaghat AS 785601 IN info@thecodeyogi.com +916900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (285,90007487,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (286,90007487,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (287,90007487,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (288,90007487,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (289,90007487,'_wc_order_attribution_session_start_time','2025-02-14 10:04:08');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (290,90007487,'_wc_order_attribution_session_pages','19');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (291,90007487,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (292,90007487,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (293,90007487,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (294,90007487,'_payment_method_id','pm_1QsNZC2HeNMDbl9ATJdED4Zk');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (295,90007487,'_stripe_customer_id','cus_RlvPeEHZkFoh9V');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (296,90007487,'_wcpay_mode','test');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (297,90007487,'_intent_id','pi_3QsNZC2HeNMDbl9A0pYQ4FUm');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (298,90007487,'_charge_id','ch_3QsNZC2HeNMDbl9A0iWgl03Y');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (299,90007487,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (300,90007487,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (301,90007487,'_wcpay_payment_transaction_id','txn_3QsNZC2HeNMDbl9A01gBB5gV');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (302,90007487,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (303,90007487,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (304,90007487,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (305,90007487,'lmfwc_order_complete','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (306,90007487,'_wcpay_transaction_fee','0.47');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (307,90007487,'_wcpay_transaction_fee','0.47');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (308,90007487,'last4','4242');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (309,90007487,'_card_brand','visa');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (310,90007487,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (311,90007491,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (312,90007491,'_billing_address_index','Anurag Handique Test 16  Test AS 201301 IN anuraghandique.dev@gmail.com 6900864982');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (313,90007491,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (314,90007491,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (315,90007491,'_wc_order_attribution_referrer','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (316,90007491,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (317,90007491,'_wc_order_attribution_session_entry','https://antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (318,90007491,'_wc_order_attribution_session_start_time','2025-06-18 06:35:00');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (319,90007491,'_wc_order_attribution_session_pages','12');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (320,90007491,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (321,90007491,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (322,90007491,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (323,90007491,'_payment_method_id','pm_1RbG9D2HeNMDbl9AAYoMvLY7');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (324,90007491,'_stripe_customer_id','cus_SWIkjZEQ8PYUOW');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (325,90007491,'_wcpay_mode','test');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (326,90007491,'_intent_id','pi_3RbG9D2HeNMDbl9A1y3bstTG');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (327,90007491,'_charge_id','ch_3RbG9D2HeNMDbl9A1qfehIIw');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (328,90007491,'_intention_status','succeeded');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (329,90007491,'_wcpay_intent_currency','usd');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (330,90007491,'_wcpay_payment_transaction_id','txn_3RbG9D2HeNMDbl9A1ojVxy0l');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (331,90007491,'_charge_risk_level','normal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (332,90007491,'_wcpay_fraud_outcome_status','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (333,90007491,'_wcpay_fraud_meta_box_type','allow');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (334,90007491,'lmfwc_order_complete','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (335,90007491,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (336,90007491,'_wcpay_transaction_fee','0.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (337,90007491,'last4','4242');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (338,90007491,'_card_brand','visa');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (339,90007491,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (340,90007491,'_new_order_tracking_complete','yes');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (342,90007660,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (343,90007660,'_billing_address_index','Hemendra Test  dettorid Kardhani mode michagan MI 48006 US hyogi067@gmail.com +19874352134');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (344,90007660,'_shipping_address_index','         +19874352134');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (345,90007660,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (346,90007660,'_wc_order_attribution_referrer','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (347,90007660,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (348,90007660,'_wc_order_attribution_session_entry','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/product/norton-360-deluxe-1-year-3-device-usa-canada-2/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (349,90007660,'_wc_order_attribution_session_start_time','2025-06-19 15:00:59');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (350,90007660,'_wc_order_attribution_session_pages','24');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (351,90007660,'_wc_order_attribution_session_count','7');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (352,90007660,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (353,90007660,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (355,90007662,'_refund_amount','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (356,90007662,'_refunded_by','12');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (357,90007662,'_refunded_payment','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (358,90007662,'_refund_reason','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (359,90007023,'lmfwc_order_complete','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (365,90007672,'_refund_amount','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (366,90007672,'_refunded_by','12');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (367,90007672,'_refunded_payment','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (368,90007672,'_refund_reason','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (370,90007732,'automatewoo_cart_id','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (371,90007732,'_billing_address_index','Hemendra Test  dettorid Kardhani mode michagan MI 48006 US hyogi067@gmail.com +19874352134');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (372,90007732,'_shipping_address_index','         +19874352134');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (373,90007732,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (374,90007732,'_wc_order_attribution_referrer','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (375,90007732,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (376,90007732,'_wc_order_attribution_session_entry','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (377,90007732,'_wc_order_attribution_session_start_time','2025-06-25 12:45:19');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (378,90007732,'_wc_order_attribution_session_pages','9');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (379,90007732,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (380,90007732,'_wc_order_attribution_user_agent','Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (381,90007732,'_wc_order_attribution_device_type','Mobile');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (382,90007732,'_automatewoo_order_created','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (383,90007732,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (385,90007744,'automatewoo_cart_id','2');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (386,90007744,'_billing_address_index','Dependra yogi internet bull 4512 North Saginaw Road APT 402 Midland MI 45008 US sxqrscym6@mozmail.com +13142394102');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (387,90007744,'_shipping_address_index','         +13142394102');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (388,90007744,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (389,90007744,'_wc_order_attribution_referrer','https://antiviruspoint.org/wp-admin/post.php?post=14&action=edit');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (390,90007744,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (391,90007744,'_wc_order_attribution_session_entry','https://antiviruspoint.org/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (392,90007744,'_wc_order_attribution_session_start_time','2025-06-27 15:05:39');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (393,90007744,'_wc_order_attribution_session_pages','49');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (394,90007744,'_wc_order_attribution_session_count','3');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (395,90007744,'_wc_order_attribution_user_agent','Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:140.0) Gecko/20100101 Firefox/140.0');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (396,90007744,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (397,90007744,'_automatewoo_order_created','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (398,90007744,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (400,90007745,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (401,90007745,'automatewoo_cart_id','3');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (402,90007745,'_billing_address_index','LOKENDRA SAINGAR  279 , rajput basti saingarpura khurd  karauli CO 45008 US Lokendra07@outlook.com +132343434');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (403,90007745,'_shipping_address_index','         +132343434');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (404,90007745,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (405,90007745,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (406,90007745,'_wc_order_attribution_session_entry','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (407,90007745,'_wc_order_attribution_session_start_time','2025-06-23 15:06:21');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (408,90007745,'_wc_order_attribution_session_pages','11');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (409,90007745,'_wc_order_attribution_session_count','12');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (410,90007745,'_wc_order_attribution_user_agent','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (411,90007745,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (412,90007745,'_automatewoo_order_created','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (414,90007801,'automatewoo_cart_id','5');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (415,90007801,'_billing_address_index','Dependra yogi internet bull 4512 North Saginaw Road APT 402 Midland MI 45008 US sxqrscym6@mozmail.com +13142394102');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (416,90007801,'_shipping_address_index','         +13142394102');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (417,90007801,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (418,90007801,'_wc_order_attribution_referrer','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/index.php');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (419,90007801,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (420,90007801,'_wc_order_attribution_session_entry','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/?hide_banners=true&preview_overlay=true');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (421,90007801,'_wc_order_attribution_session_start_time','2025-06-28 16:12:53');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (422,90007801,'_wc_order_attribution_session_pages','9');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (423,90007801,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (424,90007801,'_wc_order_attribution_user_agent','Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:140.0) Gecko/20100101 Firefox/140.0');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (425,90007801,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (426,90007801,'payoneer_ga_session_id','91069ff0e0a2d6470d174fb86d67d1f2');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (427,90007801,'_automatewoo_order_created','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (428,90007801,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (429,90007804,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (430,90007804,'automatewoo_cart_id','7');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (431,90007804,'_billing_address_index','Dependra yogi internet bull 4512 North Saginaw Road APT 402 Midland MI 45008 US sxqrscym6@mozmail.com +13142394102');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (432,90007804,'_shipping_address_index','         +13142394102');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (433,90007804,'_wc_order_attribution_source_type','referral');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (434,90007804,'_wc_order_attribution_referrer','https://tagassistant.google.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (435,90007804,'_wc_order_attribution_utm_source','tagassistant.google.com');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (436,90007804,'_wc_order_attribution_utm_medium','referral');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (437,90007804,'_wc_order_attribution_utm_content','/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (438,90007804,'_wc_order_attribution_session_entry','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/?gtm_debug=1751149906692');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (439,90007804,'_wc_order_attribution_session_start_time','2025-06-28 23:01:53');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (440,90007804,'_wc_order_attribution_session_pages','22');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (441,90007804,'_wc_order_attribution_session_count','4');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (442,90007804,'_wc_order_attribution_user_agent','Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:140.0) Gecko/20100101 Firefox/140.0');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (443,90007804,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (444,90007804,'payoneer_ga_session_id','91069ff0e0a2d6470d174fb86d67d1f2');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (445,90007804,'_automatewoo_order_created','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (447,90007894,'automatewoo_cart_id','14');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (448,90007894,'_billing_address_index','LOKENDRA Test  61 uttam nagar behind power house Kardhani mode Jaipur MI 48069 US mohu3001@gmail.com +917877180969');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (449,90007894,'_shipping_address_index','         +917877180969');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (450,90007894,'mailchimp_woocommerce_landing_site','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/checkout/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (451,90007894,'_wc_order_attribution_source_type','typein');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (452,90007894,'_wc_order_attribution_referrer','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/product/malwarebytes-premium-for-mac-1-year-1-mac/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (453,90007894,'_wc_order_attribution_utm_source','(direct)');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (454,90007894,'_wc_order_attribution_session_entry','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/checkout/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (455,90007894,'_wc_order_attribution_session_start_time','2025-07-01 19:55:55');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (456,90007894,'_wc_order_attribution_session_pages','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (457,90007894,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (458,90007894,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (459,90007894,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (461,90007894,'_automatewoo_order_created','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (463,90007894,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (465,90007926,'_billing_address_index','Thomas VanCaster       US tomvancaster@yahoo.com 2628182869');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (466,90007926,'_shipping_address_index','         ');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (467,90007926,'mailchimp_woocommerce_landing_site','https://staging-bf5f-antiviruspointorgdomainonly.wpcomstaging.com/wp-admin/undefined?h=288');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (468,90007926,'_ppcp_paypal_order_id','4ER323924F0921443');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (469,90007926,'_ppcp_paypal_intent','AUTHORIZE');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (470,90007926,'_ppcp_paypal_payment_mode','live');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (471,90007926,'_ppcp_paypal_payment_source','paypal');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (472,90007926,'_ppcp_paypal_payer_email','tomvancaster@yahoo.com');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (473,90007926,'_ppcp_paypal_captured','false');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (474,90007926,'_automatewoo_order_created','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (476,90007926,'_meta_purchase_tracked','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (477,90008040,'_refund_amount','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (478,90008040,'_refunded_by','0');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (479,90008040,'_refunded_payment','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (480,90008040,'_refund_reason','');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (481,90007926,'_ppcp_refunds','a:1:{i:0;s:17:\"7HY32154WK4527704\";}');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (482,90007926,'_ppcp_paypal_refund_fees','a:3:{s:12:\"gross_amount\";a:2:{s:13:\"currency_code\";s:0:\"\";s:5:\"value\";s:4:\"0.00\";}s:10:\"paypal_fee\";a:2:{s:13:\"currency_code\";s:0:\"\";s:5:\"value\";s:4:\"0.00\";}s:10:\"net_amount\";a:2:{s:13:\"currency_code\";s:0:\"\";s:5:\"value\";s:4:\"0.00\";}}');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (483,90007926,'_receipt_file_name','7e9817afff0753eeb9f3ac728a021820f2d3f3');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (484,90008190,'is_vat_exempt','no');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (485,90008190,'_billing_address_index','Astitva Pathak  Kailashpuri Road Tikrapara near Sahu Murti Bhandar  Raipur CA 90001 US astitva@gmail.com 7389522364');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (486,90008190,'_shipping_address_index','         7389522364');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (487,90008190,'mailchimp_woocommerce_landing_site','https://antiviruspoint.org/wp-admin/undefined?h=288');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (488,90008190,'mailchimp_woocommerce_is_subscribed','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (489,90008190,'_wc_order_attribution_source_type','referral');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (490,90008190,'_wc_order_attribution_referrer','https://www.linkedin.com/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (491,90008190,'_wc_order_attribution_utm_source','linkedin.com');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (492,90008190,'_wc_order_attribution_utm_medium','referral');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (493,90008190,'_wc_order_attribution_utm_content','/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (494,90008190,'_wc_order_attribution_session_entry','https://antiviruspoint.org/');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (495,90008190,'_wc_order_attribution_session_start_time','2025-09-03 17:40:23');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (496,90008190,'_wc_order_attribution_session_pages','10');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (497,90008190,'_wc_order_attribution_session_count','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (498,90008190,'_wc_order_attribution_user_agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (499,90008190,'_wc_order_attribution_device_type','Desktop');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (500,90008190,'_meta_purchase_tracked','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (501,90008190,'_automatewoo_order_created','1');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (503,90008190,'_receipt_file_name','7e9905017237907fe8177fde495d260e9bb603');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (507,90007744,'mailchimp_woocommerce_landing_site','https://antiviruspoint.org/wp-admin/undefinedjetpack/v4/site/benefits?_cacheBuster=1757045165624');
INSERT INTO `fqsi_wc_orders_meta` (`id`, `order_id`, `meta_key`, `meta_value`) VALUES (508,90008040,'_refund_type','full');
